/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from 'ethers';
import type {
  ProfitShareVaultProviderStateAggregator_v1,
  ProfitShareVaultProviderStateAggregator_v1Interface,
} from '../ProfitShareVaultProviderStateAggregator_v1';

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: 'profitShareVaultProvider_',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [
      {
        internalType: 'address[]',
        name: 'managerWallets',
        type: 'address[]',
      },
    ],
    name: 'loadSharePricesAndTotalSharesByVaults',
    outputs: [
      {
        components: [
          {
            internalType: 'uint64',
            name: 'sharePrice',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'totalShares',
            type: 'uint64',
          },
        ],
        internalType: 'struct LoadSharePricesAndTotalSharesResult[]',
        name: 'loadSharePricesAndTotalSharesResults',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address[]',
        name: 'managerWallets',
        type: 'address[]',
      },
      {
        internalType: 'address',
        name: 'wallet',
        type: 'address',
      },
    ],
    name: 'loadVaultDepositorsByDepositorWallet',
    outputs: [
      {
        components: [
          {
            internalType: 'uint64',
            name: 'costBasis',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'sharePrice',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'totalShares',
            type: 'uint64',
          },
        ],
        internalType: 'struct LoadVaultDepositorsResult[]',
        name: 'loadVaultDepositorsResults',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
      {
        internalType: 'address[]',
        name: 'wallets',
        type: 'address[]',
      },
    ],
    name: 'loadVaultDepositorsByManagerWallet',
    outputs: [
      {
        components: [
          {
            internalType: 'uint64',
            name: 'costBasis',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'sharePrice',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'totalShares',
            type: 'uint64',
          },
        ],
        internalType: 'struct LoadVaultDepositorsResult[]',
        name: 'loadVaultDepositorsResults',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
    ],
    name: 'loadVaultWithdrawalQueue',
    outputs: [
      {
        components: [
          {
            internalType: 'uint128',
            name: 'nonce',
            type: 'uint128',
          },
          {
            internalType: 'address',
            name: 'depositorWallet',
            type: 'address',
          },
          {
            internalType: 'uint64',
            name: 'shares',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'minimumQuantity',
            type: 'uint64',
          },
        ],
        internalType: 'struct VaultWithdrawQueueItem[]',
        name: 'loadVaultWithdrawalQueueResults',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'profitShareVaultProvider',
    outputs: [
      {
        internalType: 'contract ProfitShareVaultProvider_v1',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export class ProfitShareVaultProviderStateAggregator_v1__factory {
  static readonly abi = _abi;
  static createInterface(): ProfitShareVaultProviderStateAggregator_v1Interface {
    return new Interface(
      _abi,
    ) as ProfitShareVaultProviderStateAggregator_v1Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null,
  ): ProfitShareVaultProviderStateAggregator_v1 {
    return new Contract(
      address,
      _abi,
      runner,
    ) as unknown as ProfitShareVaultProviderStateAggregator_v1;
  }
}
