/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from 'ethers';
import type {
  ProfitShareVaultProvider_v1,
  ProfitShareVaultProvider_v1Interface,
} from '../ProfitShareVaultProvider_v1';

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: 'exchange_',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [],
    name: 'AddManagedAccountDisabled',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
    ],
    name: 'ApplyDepositDisabled',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'value',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'maxValue',
        type: 'uint64',
      },
    ],
    name: 'CarryFeeMultiplierOutOfRange',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
    ],
    name: 'DepositDisabled',
    type: 'error',
  },
  {
    inputs: [],
    name: 'DepositExceedsMax',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'value',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'maxValue',
        type: 'uint64',
      },
    ],
    name: 'DepositFeeMultiplierOutOfRange',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint128',
        name: 'maxValue',
        type: 'uint128',
      },
    ],
    name: 'DepositQueueLengthExceedsMax',
    type: 'error',
  },
  {
    inputs: [],
    name: 'Duplicate',
    type: 'error',
  },
  {
    inputs: [],
    name: 'ECDSAInvalidSignature',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'length',
        type: 'uint256',
      },
    ],
    name: 'ECDSAInvalidSignatureLength',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: 's',
        type: 'bytes32',
      },
    ],
    name: 'ECDSAInvalidSignatureS',
    type: 'error',
  },
  {
    inputs: [],
    name: 'ExitFundCannotHaveOpenPosition',
    type: 'error',
  },
  {
    inputs: [],
    name: 'ExitFundHasNoPositions',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'actual',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'expected',
        type: 'uint256',
      },
    ],
    name: 'InsufficientQuoteBalance',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'available',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'required',
        type: 'uint64',
      },
    ],
    name: 'InsufficientShares',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'actualTimestampInS',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'expectedTimestampInS',
        type: 'uint256',
      },
    ],
    name: 'IntervalTickTooSoon',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidContractAddress',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'depositIndex',
        type: 'uint64',
      },
    ],
    name: 'InvalidDepositIndex',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidDepositorWallet',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidManagerWallet',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidQuantity',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidWalletAddress',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidWalletSignature',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'actualQuantity',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'expectedQuantity',
        type: 'uint64',
      },
    ],
    name: 'InvalidWithdrawalGrossQuoteQuantity',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: 'withdrawalHash',
        type: 'bytes32',
      },
    ],
    name: 'InvalidWithdrawalHash',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'value',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'maxValue',
        type: 'uint64',
      },
    ],
    name: 'ManagementFeeMultiplierOutOfRange',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'value',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'maxValue',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'minValue',
        type: 'uint64',
      },
    ],
    name: 'ManagementFeePeriodOutOfRange',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'maxValue',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'value',
        type: 'uint64',
      },
    ],
    name: 'MaximumGasFeeExceedsQuantity',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'minValue',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'value',
        type: 'uint64',
      },
    ],
    name: 'MaximumGasFeeTooLow',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'value',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'maxValue',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'minValue',
        type: 'uint64',
      },
    ],
    name: 'MaximumNetDepositsOutOfRange',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'value',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'maxValue',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'minValue',
        type: 'uint64',
      },
    ],
    name: 'MinimumUnappliedWithdrawalAgeInSToInitiateExitOutOfRange',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'value',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'maxValue',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'minValue',
        type: 'uint64',
      },
    ],
    name: 'MinimumWithdrawalQuantityOutOfRange',
    type: 'error',
  },
  {
    inputs: [],
    name: 'NewInsuranceFundWalletCannotBeExited',
    type: 'error',
  },
  {
    inputs: [],
    name: 'NewValueExceedsMaximum',
    type: 'error',
  },
  {
    inputs: [],
    name: 'NewValueMustBeDifferentFromCurrent',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'value',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'maxValue',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'minValue',
        type: 'uint64',
      },
    ],
    name: 'NonceTimestampSkewOutOfRange',
    type: 'error',
  },
  {
    inputs: [],
    name: 'NotFound',
    type: 'error',
  },
  {
    inputs: [],
    name: 'NotImplemented',
    type: 'error',
  },
  {
    inputs: [],
    name: 'SenderMustBeAdmin',
    type: 'error',
  },
  {
    inputs: [],
    name: 'SenderMustBeAdminOrDispatcher',
    type: 'error',
  },
  {
    inputs: [],
    name: 'SenderMustBeDepositorWallet',
    type: 'error',
  },
  {
    inputs: [],
    name: 'SenderMustBeDispatcher',
    type: 'error',
  },
  {
    inputs: [],
    name: 'SenderMustBeExchange',
    type: 'error',
  },
  {
    inputs: [],
    name: 'SenderMustBeExchangeBridgeAdapter',
    type: 'error',
  },
  {
    inputs: [],
    name: 'SenderMustBeGovernance',
    type: 'error',
  },
  {
    inputs: [],
    name: 'SenderMustBeOwner',
    type: 'error',
  },
  {
    inputs: [],
    name: 'SenderMustBeWithdrawalDispatcher',
    type: 'error',
  },
  {
    inputs: [],
    name: 'TotalAccountValueIsNegative',
    type: 'error',
  },
  {
    inputs: [],
    name: 'UnknownBaseAssetSymbol',
    type: 'error',
  },
  {
    inputs: [],
    name: 'ValueCanOnlyBetSetOnce',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'actual',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'expected',
        type: 'uint256',
      },
    ],
    name: 'VaultConfigurationUpgradeBlockTimestampThresholdNotReached',
    type: 'error',
  },
  {
    inputs: [],
    name: 'VaultConfigurationUpgradeNotInProgress',
    type: 'error',
  },
  {
    inputs: [],
    name: 'VaultIsExitFinalized',
    type: 'error',
  },
  {
    inputs: [],
    name: 'VaultIsExited',
    type: 'error',
  },
  {
    inputs: [],
    name: 'VaultIsLiquidated',
    type: 'error',
  },
  {
    inputs: [],
    name: 'VaultIsNotExited',
    type: 'error',
  },
  {
    inputs: [],
    name: 'WalletCannotBeExited',
    type: 'error',
  },
  {
    inputs: [],
    name: 'WalletHasNoOverridesForMarket',
    type: 'error',
  },
  {
    inputs: [],
    name: 'WalletMustBeExited',
    type: 'error',
  },
  {
    inputs: [],
    name: 'WithdrawalCancellationNotAllowed',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'minValue',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'value',
        type: 'uint64',
      },
    ],
    name: 'WithdrawalQuantityBelowMinimum',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'limit',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'value',
        type: 'uint64',
      },
    ],
    name: 'WithdrawalQuantityExceedsLimit',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'AddManagedAccountsDisabledAdmin',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'AddManagedAccountsEnabledAdmin',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint64',
        name: 'depositIndex',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'quantity',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'sourceWallet',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'depositorWallet',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
    ],
    name: 'DepositToManagedAccountReadyToApply',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
    ],
    name: 'DepositsDisabled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'bool',
        name: 'isDepositEnabled',
        type: 'bool',
      },
      {
        indexed: false,
        internalType: 'bool',
        name: 'isApplyDepositEnabled',
        type: 'bool',
      },
    ],
    name: 'DepositsDisabledAdmin',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
    ],
    name: 'DepositsEnabled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'DepositsEnabledAdmin',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'depositorWallet',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'quantityInAssetUnits',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'bytes',
        name: 'depositErrorData',
        type: 'bytes',
      },
    ],
    name: 'LiquidatedVaultPendingDepositRefundFailed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
    ],
    name: 'ManagedAccountAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'previousValue',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'newValue',
        type: 'uint256',
      },
    ],
    name: 'ManagedAccountUpgradeBlockTimestampDelayChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
    ],
    name: 'ManagedAccountUpgradeCanceled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
    ],
    name: 'ManagedAccountUpgradeFinalized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'blockTimestampThreshold',
        type: 'uint256',
      },
    ],
    name: 'ManagedAccountUpgradeInitiated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'previousValue',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'newValue',
        type: 'uint256',
      },
    ],
    name: 'MinimumWithdrawalQuantityChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
    ],
    name: 'VaultLiquidated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'depositorWallet',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'sharesBurned',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'quoteQuantity',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'totalSharesForWallet',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'totalSharesForVault',
        type: 'uint64',
      },
    ],
    name: 'VaultSharesBurned',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'depositorWallet',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'sharesMinted',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'totalSharesForWallet',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'totalSharesForVault',
        type: 'uint64',
      },
    ],
    name: 'VaultSharesMinted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'previousValue',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'newValue',
        type: 'address',
      },
    ],
    name: 'WithdrawalDispatcherChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'depositorWallet',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'shares',
        type: 'uint64',
      },
    ],
    name: 'WithdrawalFromManagedAccountCanceled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            internalType: 'enum ManagedAccountWithdrawalType',
            name: 'withdrawalType',
            type: 'uint8',
          },
          {
            components: [
              {
                internalType: 'uint128',
                name: 'nonce',
                type: 'uint128',
              },
              {
                internalType: 'address',
                name: 'managerWallet',
                type: 'address',
              },
              {
                internalType: 'address',
                name: 'depositorWallet',
                type: 'address',
              },
              {
                internalType: 'uint64',
                name: 'grossQuantity',
                type: 'uint64',
              },
              {
                internalType: 'uint64',
                name: 'maxShares',
                type: 'uint64',
              },
              {
                internalType: 'uint64',
                name: 'maximumGasFee',
                type: 'uint64',
              },
              {
                internalType: 'contract IManagedAccountProvider',
                name: 'managedAccountProvider',
                type: 'address',
              },
              {
                internalType: 'bytes',
                name: 'managedAccountProviderPayload',
                type: 'bytes',
              },
              {
                internalType: 'address',
                name: 'bridgeAdapter',
                type: 'address',
              },
              {
                internalType: 'bytes',
                name: 'bridgeAdapterPayload',
                type: 'bytes',
              },
              {
                internalType: 'uint64',
                name: 'gasFee',
                type: 'uint64',
              },
              {
                internalType: 'bytes',
                name: 'walletSignature',
                type: 'bytes',
              },
            ],
            internalType: 'struct WithdrawalFromManagedAccountByQuantity',
            name: 'withdrawalByQuantity',
            type: 'tuple',
          },
          {
            components: [
              {
                internalType: 'uint128',
                name: 'nonce',
                type: 'uint128',
              },
              {
                internalType: 'address',
                name: 'managerWallet',
                type: 'address',
              },
              {
                internalType: 'address',
                name: 'depositorWallet',
                type: 'address',
              },
              {
                internalType: 'uint64',
                name: 'shares',
                type: 'uint64',
              },
              {
                internalType: 'uint64',
                name: 'minimumQuantity',
                type: 'uint64',
              },
              {
                internalType: 'uint64',
                name: 'maximumGasFee',
                type: 'uint64',
              },
              {
                internalType: 'contract IManagedAccountProvider',
                name: 'managedAccountProvider',
                type: 'address',
              },
              {
                internalType: 'bytes',
                name: 'managedAccountProviderPayload',
                type: 'bytes',
              },
              {
                internalType: 'address',
                name: 'bridgeAdapter',
                type: 'address',
              },
              {
                internalType: 'bytes',
                name: 'bridgeAdapterPayload',
                type: 'bytes',
              },
              {
                internalType: 'uint64',
                name: 'gasFee',
                type: 'uint64',
              },
              {
                internalType: 'uint64',
                name: 'grossQuantity',
                type: 'uint64',
              },
              {
                internalType: 'bytes',
                name: 'walletSignature',
                type: 'bytes',
              },
            ],
            internalType: 'struct WithdrawalFromManagedAccountByShares',
            name: 'withdrawalByShares',
            type: 'tuple',
          },
        ],
        indexed: false,
        internalType: 'struct WithdrawalFromManagedAccount',
        name: 'withdrawal',
        type: 'tuple',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'totalShareSupply',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'numberOfWithdrawalsInQueue',
        type: 'uint256',
      },
    ],
    name: 'WithdrawalFromManagedAccountReadyToApply',
    type: 'event',
  },
  {
    inputs: [],
    name: 'INITIAL_SHARE_PRICE',
    outputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_CARRY_FEE_MULTIPLIER',
    outputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_DEPOSIT_FEE_MULTIPLIER',
    outputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_MANAGEMENT_FEE_MULTIPLIER',
    outputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_MANAGEMENT_FEE_PERIOD_IN_S',
    outputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_MAXIMUM_NET_DEPOSITS',
    outputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_MINIMUM_UNAPPLIED_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT',
    outputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_MINIMUM_WITHDRAWAL_QUANTITY',
    outputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MIN_MANAGEMENT_FEE_PERIOD_IN_S',
    outputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MIN_MAXIMUM_NET_DEPOSITS',
    outputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MIN_MINIMUM_UNAPPLIED_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT',
    outputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MIN_MINIMUM_WITHDRAWAL_QUANTITY',
    outputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'WORD_SIZE_IN_BYTES',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
      {
        internalType: 'bytes',
        name: 'payload',
        type: 'bytes',
      },
    ],
    name: 'addManagedAccount',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'adminWallet',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'depositIndex',
        type: 'uint64',
      },
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
      {
        internalType: 'uint64',
        name: 'quantity',
        type: 'uint64',
      },
    ],
    name: 'applyPendingDeposit',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'gasFee',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'grossQuantity',
        type: 'uint64',
      },
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
      {
        internalType: 'bytes32',
        name: 'withdrawalHash',
        type: 'bytes32',
      },
    ],
    name: 'applyPendingWithdrawal',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'cancelManagedAccountUpgrade',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'gasFee',
        type: 'uint64',
      },
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
      {
        internalType: 'bytes32',
        name: 'withdrawalHash',
        type: 'bytes32',
      },
    ],
    name: 'cancelPendingWithdrawal',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'depositIndex',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'quantity',
        type: 'uint64',
      },
      {
        internalType: 'address',
        name: 'sourceWallet',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'depositorWallet',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
      {
        internalType: 'bytes',
        name: 'payload',
        type: 'bytes',
      },
    ],
    name: 'deposit',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
    ],
    name: 'emitEventsForFrontOfDepositAndWithdrawalQueues',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'exchange',
    outputs: [
      {
        internalType: 'contract IExchange',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
    ],
    name: 'exitWallet',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'finalizeManagedAccountUpgrade',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes',
        name: 'payload',
        type: 'bytes',
      },
    ],
    name: 'initiateManagedAccountUpgrade',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes',
        name: 'payload',
        type: 'bytes',
      },
    ],
    name: 'intervalTick',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'isAddManagedAccountEnabled',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    name: 'isApplyDepositEnabled',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
    ],
    name: 'isDepositEnabled',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
    ],
    name: 'liquidateManagerWallet',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
    ],
    name: 'loadSharePrice',
    outputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'depositorWallet',
        type: 'address',
      },
    ],
    name: 'loadVaultBalanceForWallet',
    outputs: [
      {
        components: [
          {
            internalType: 'uint64',
            name: 'costBasis',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'sharesLockedForWithdrawal',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'totalShares',
            type: 'uint64',
          },
        ],
        internalType:
          'struct ProfitShareVaultProvider_v1.VaultBalanceForWallet',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'index',
        type: 'uint256',
      },
    ],
    name: 'loadVaultDepositQueueItem',
    outputs: [
      {
        components: [
          {
            internalType: 'uint64',
            name: 'index',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'quantity',
            type: 'uint64',
          },
          {
            internalType: 'address',
            name: 'sourceWallet',
            type: 'address',
          },
          {
            internalType: 'address',
            name: 'depositorWallet',
            type: 'address',
          },
          {
            internalType: 'address',
            name: 'managerWallet',
            type: 'address',
          },
          {
            internalType: 'contract IManagedAccountProvider',
            name: 'managedAccount',
            type: 'address',
          },
          {
            internalType: 'bytes',
            name: 'payload',
            type: 'bytes',
          },
        ],
        internalType: 'struct VaultDepositQueue.Item',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
    ],
    name: 'loadVaultDepositQueueLength',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
    ],
    name: 'loadVaultSummary',
    outputs: [
      {
        components: [
          {
            internalType: 'bool',
            name: 'isDepositEnabled',
            type: 'bool',
          },
          {
            internalType: 'bool',
            name: 'isExited',
            type: 'bool',
          },
          {
            internalType: 'bool',
            name: 'isLiquidated',
            type: 'bool',
          },
          {
            components: [
              {
                internalType: 'address',
                name: 'managerWallet',
                type: 'address',
              },
              {
                internalType: 'uint64',
                name: 'carryFeeMultiplier',
                type: 'uint64',
              },
              {
                internalType: 'uint64',
                name: 'depositFeeMultiplier',
                type: 'uint64',
              },
              {
                internalType: 'uint64',
                name: 'managementFeeMultiplier',
                type: 'uint64',
              },
              {
                internalType: 'uint64',
                name: 'managementFeePeriodInS',
                type: 'uint64',
              },
              {
                internalType: 'uint64',
                name: 'maximumNetDeposits',
                type: 'uint64',
              },
              {
                internalType: 'uint64',
                name: 'minimumUnappliedWithdrawalAgeInSToInitiateExit',
                type: 'uint64',
              },
            ],
            internalType:
              'struct ProfitShareVaultProvider_v1.VaultConfigurationFields',
            name: 'configurationFields',
            type: 'tuple',
          },
          {
            internalType: 'uint64',
            name: 'netDeposits',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'numDepositorWallets',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'sharePrice',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'totalShares',
            type: 'uint64',
          },
        ],
        internalType: 'struct ProfitShareVaultProvider_v1.VaultSummary',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'index',
        type: 'uint256',
      },
    ],
    name: 'loadVaultWithdrawQueueItem',
    outputs: [
      {
        components: [
          {
            internalType: 'enum ManagedAccountWithdrawalType',
            name: 'withdrawalType',
            type: 'uint8',
          },
          {
            components: [
              {
                internalType: 'uint128',
                name: 'nonce',
                type: 'uint128',
              },
              {
                internalType: 'address',
                name: 'managerWallet',
                type: 'address',
              },
              {
                internalType: 'address',
                name: 'depositorWallet',
                type: 'address',
              },
              {
                internalType: 'uint64',
                name: 'grossQuantity',
                type: 'uint64',
              },
              {
                internalType: 'uint64',
                name: 'maxShares',
                type: 'uint64',
              },
              {
                internalType: 'uint64',
                name: 'maximumGasFee',
                type: 'uint64',
              },
              {
                internalType: 'contract IManagedAccountProvider',
                name: 'managedAccountProvider',
                type: 'address',
              },
              {
                internalType: 'bytes',
                name: 'managedAccountProviderPayload',
                type: 'bytes',
              },
              {
                internalType: 'address',
                name: 'bridgeAdapter',
                type: 'address',
              },
              {
                internalType: 'bytes',
                name: 'bridgeAdapterPayload',
                type: 'bytes',
              },
              {
                internalType: 'uint64',
                name: 'gasFee',
                type: 'uint64',
              },
              {
                internalType: 'bytes',
                name: 'walletSignature',
                type: 'bytes',
              },
            ],
            internalType: 'struct WithdrawalFromManagedAccountByQuantity',
            name: 'withdrawalByQuantity',
            type: 'tuple',
          },
          {
            components: [
              {
                internalType: 'uint128',
                name: 'nonce',
                type: 'uint128',
              },
              {
                internalType: 'address',
                name: 'managerWallet',
                type: 'address',
              },
              {
                internalType: 'address',
                name: 'depositorWallet',
                type: 'address',
              },
              {
                internalType: 'uint64',
                name: 'shares',
                type: 'uint64',
              },
              {
                internalType: 'uint64',
                name: 'minimumQuantity',
                type: 'uint64',
              },
              {
                internalType: 'uint64',
                name: 'maximumGasFee',
                type: 'uint64',
              },
              {
                internalType: 'contract IManagedAccountProvider',
                name: 'managedAccountProvider',
                type: 'address',
              },
              {
                internalType: 'bytes',
                name: 'managedAccountProviderPayload',
                type: 'bytes',
              },
              {
                internalType: 'address',
                name: 'bridgeAdapter',
                type: 'address',
              },
              {
                internalType: 'bytes',
                name: 'bridgeAdapterPayload',
                type: 'bytes',
              },
              {
                internalType: 'uint64',
                name: 'gasFee',
                type: 'uint64',
              },
              {
                internalType: 'uint64',
                name: 'grossQuantity',
                type: 'uint64',
              },
              {
                internalType: 'bytes',
                name: 'walletSignature',
                type: 'bytes',
              },
            ],
            internalType: 'struct WithdrawalFromManagedAccountByShares',
            name: 'withdrawalByShares',
            type: 'tuple',
          },
        ],
        internalType: 'struct WithdrawalFromManagedAccount',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
    ],
    name: 'loadVaultWithdrawQueueLength',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'managedAccountUpgradeBlockTimestampDelayInS',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'minimumWithdrawalQuantity',
    outputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'ownerWallet',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'removeAdmin',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'removeOwner',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64',
      },
    ],
    name: 'seenDepositIndexes',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    name: 'seenWithdrawalHashes',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bool',
        name: 'isAddManagedAccountEnabled',
        type: 'bool',
      },
    ],
    name: 'setAddManagedAccountEnabledAdmin',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'newAdmin',
        type: 'address',
      },
    ],
    name: 'setAdmin',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bool',
        name: 'isEnabled',
        type: 'bool',
      },
    ],
    name: 'setDepositEnabled',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bool',
        name: 'isDepositEnabled',
        type: 'bool',
      },
      {
        internalType: 'bool',
        name: 'isApplyDepositEnabled',
        type: 'bool',
      },
    ],
    name: 'setDepositEnabledAdmin',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'newManagedAccountUpgradeBlockTimestampDelayInS',
        type: 'uint256',
      },
    ],
    name: 'setManagedAccountUpgradeBlockTimestampDelay',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'newMinimumWithdrawalQuantity',
        type: 'uint64',
      },
    ],
    name: 'setMinimumWithdrawalQuantity',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'setOwner',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'newWithdrawalDispatcherWallet',
        type: 'address',
      },
    ],
    name: 'setWithdrawalDispatcher',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'tokenAddress',
        type: 'address',
      },
    ],
    name: 'skim',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    name: 'vaultConfigurationUpgradesByManagerWallet',
    outputs: [
      {
        internalType: 'bool',
        name: 'exists',
        type: 'bool',
      },
      {
        components: [
          {
            internalType: 'address',
            name: 'managerWallet',
            type: 'address',
          },
          {
            internalType: 'uint64',
            name: 'carryFeeMultiplier',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'depositFeeMultiplier',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'managementFeeMultiplier',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'managementFeePeriodInS',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'maximumNetDeposits',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'minimumUnappliedWithdrawalAgeInSToInitiateExit',
            type: 'uint64',
          },
        ],
        internalType:
          'struct ProfitShareVaultProvider_v1.VaultConfigurationFields',
        name: 'newVaultConfigurationFields',
        type: 'tuple',
      },
      {
        internalType: 'uint256',
        name: 'blockTimestampThreshold',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: 'uint128',
            name: 'nonce',
            type: 'uint128',
          },
          {
            internalType: 'address',
            name: 'managerWallet',
            type: 'address',
          },
          {
            internalType: 'address',
            name: 'depositorWallet',
            type: 'address',
          },
          {
            internalType: 'uint64',
            name: 'grossQuantity',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'maxShares',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'maximumGasFee',
            type: 'uint64',
          },
          {
            internalType: 'contract IManagedAccountProvider',
            name: 'managedAccountProvider',
            type: 'address',
          },
          {
            internalType: 'bytes',
            name: 'managedAccountProviderPayload',
            type: 'bytes',
          },
          {
            internalType: 'address',
            name: 'bridgeAdapter',
            type: 'address',
          },
          {
            internalType: 'bytes',
            name: 'bridgeAdapterPayload',
            type: 'bytes',
          },
          {
            internalType: 'uint64',
            name: 'gasFee',
            type: 'uint64',
          },
          {
            internalType: 'bytes',
            name: 'walletSignature',
            type: 'bytes',
          },
        ],
        internalType: 'struct WithdrawalFromManagedAccountByQuantity',
        name: '',
        type: 'tuple',
      },
    ],
    name: 'withdrawByQuantity',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: 'uint128',
            name: 'nonce',
            type: 'uint128',
          },
          {
            internalType: 'address',
            name: 'managerWallet',
            type: 'address',
          },
          {
            internalType: 'address',
            name: 'depositorWallet',
            type: 'address',
          },
          {
            internalType: 'uint64',
            name: 'shares',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'minimumQuantity',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'maximumGasFee',
            type: 'uint64',
          },
          {
            internalType: 'contract IManagedAccountProvider',
            name: 'managedAccountProvider',
            type: 'address',
          },
          {
            internalType: 'bytes',
            name: 'managedAccountProviderPayload',
            type: 'bytes',
          },
          {
            internalType: 'address',
            name: 'bridgeAdapter',
            type: 'address',
          },
          {
            internalType: 'bytes',
            name: 'bridgeAdapterPayload',
            type: 'bytes',
          },
          {
            internalType: 'uint64',
            name: 'gasFee',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'grossQuantity',
            type: 'uint64',
          },
          {
            internalType: 'bytes',
            name: 'walletSignature',
            type: 'bytes',
          },
        ],
        internalType: 'struct WithdrawalFromManagedAccountByShares',
        name: 'withdrawal',
        type: 'tuple',
      },
    ],
    name: 'withdrawByShares',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'managerWallet',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'depositorWallet',
        type: 'address',
      },
    ],
    name: 'withdrawExit',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'withdrawalDispatcherWallet',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export class ProfitShareVaultProvider_v1__factory {
  static readonly abi = _abi;
  static createInterface(): ProfitShareVaultProvider_v1Interface {
    return new Interface(_abi) as ProfitShareVaultProvider_v1Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null,
  ): ProfitShareVaultProvider_v1 {
    return new Contract(
      address,
      _abi,
      runner,
    ) as unknown as ProfitShareVaultProvider_v1;
  }
}
