/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from './common';

export interface EarningsEscrow_v2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | 'acceptOwnership'
      | 'bulkAssignOwedQuantities'
      | 'distribute'
      | 'distributedQuantityByWallet'
      | 'exchange'
      | 'isDistributeEnabled'
      | 'owedQuantityByWallet'
      | 'owner'
      | 'pendingOwner'
      | 'quoteAsset'
      | 'renounceOwnership'
      | 'setDistributeEnabled'
      | 'totalOwedQuantity'
      | 'transferOwnership'
      | 'withdrawEscrow',
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | 'AssetsDistributed'
      | 'EscrowWithdrawn'
      | 'OwnershipTransferStarted'
      | 'OwnershipTransferred',
  ): EventFragment;

  encodeFunctionData(
    functionFragment: 'acceptOwnership',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'bulkAssignOwedQuantities',
    values: [AddressLike[], BigNumberish[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'distribute',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'distributedQuantityByWallet',
    values: [AddressLike],
  ): string;
  encodeFunctionData(functionFragment: 'exchange', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'isDistributeEnabled',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'owedQuantityByWallet',
    values: [AddressLike],
  ): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'pendingOwner',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'quoteAsset',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'renounceOwnership',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'setDistributeEnabled',
    values: [boolean],
  ): string;
  encodeFunctionData(
    functionFragment: 'totalOwedQuantity',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'withdrawEscrow',
    values: [BigNumberish],
  ): string;

  decodeFunctionResult(
    functionFragment: 'acceptOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'bulkAssignOwedQuantities',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'distribute', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'distributedQuantityByWallet',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'exchange', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'isDistributeEnabled',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'owedQuantityByWallet',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'pendingOwner',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'quoteAsset', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'renounceOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setDistributeEnabled',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'totalOwedQuantity',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'withdrawEscrow',
    data: BytesLike,
  ): Result;
}

export namespace AssetsDistributedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    quantity: BigNumberish,
    newTotalOwedQuantity: BigNumberish,
  ];
  export type OutputTuple = [
    wallet: string,
    quantity: bigint,
    newTotalOwedQuantity: bigint,
  ];
  export interface OutputObject {
    wallet: string;
    quantity: bigint;
    newTotalOwedQuantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowWithdrawnEvent {
  export type InputTuple = [
    ownerWallet: AddressLike,
    quantity: BigNumberish,
    newEscrowBalance: BigNumberish,
  ];
  export type OutputTuple = [
    ownerWallet: string,
    quantity: bigint,
    newEscrowBalance: bigint,
  ];
  export interface OutputObject {
    ownerWallet: string;
    quantity: bigint;
    newEscrowBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EarningsEscrow_v2 extends BaseContract {
  connect(runner?: ContractRunner | null): EarningsEscrow_v2;
  waitForDeployment(): Promise<this>;

  interface: EarningsEscrow_v2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], 'nonpayable'>;

  bulkAssignOwedQuantities: TypedContractMethod<
    [wallets: AddressLike[], newOwedQuantities: BigNumberish[]],
    [void],
    'nonpayable'
  >;

  distribute: TypedContractMethod<
    [walletAddress: AddressLike],
    [void],
    'nonpayable'
  >;

  distributedQuantityByWallet: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    'view'
  >;

  exchange: TypedContractMethod<[], [string], 'view'>;

  isDistributeEnabled: TypedContractMethod<[], [boolean], 'view'>;

  owedQuantityByWallet: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    'view'
  >;

  owner: TypedContractMethod<[], [string], 'view'>;

  pendingOwner: TypedContractMethod<[], [string], 'view'>;

  quoteAsset: TypedContractMethod<[], [string], 'view'>;

  renounceOwnership: TypedContractMethod<[], [void], 'nonpayable'>;

  setDistributeEnabled: TypedContractMethod<
    [isEnabled: boolean],
    [void],
    'nonpayable'
  >;

  totalOwedQuantity: TypedContractMethod<[], [bigint], 'view'>;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    'nonpayable'
  >;

  withdrawEscrow: TypedContractMethod<
    [quantity: BigNumberish],
    [void],
    'nonpayable'
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: 'acceptOwnership',
  ): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'bulkAssignOwedQuantities',
  ): TypedContractMethod<
    [wallets: AddressLike[], newOwedQuantities: BigNumberish[]],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'distribute',
  ): TypedContractMethod<[walletAddress: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'distributedQuantityByWallet',
  ): TypedContractMethod<[arg0: AddressLike], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'exchange',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'isDistributeEnabled',
  ): TypedContractMethod<[], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'owedQuantityByWallet',
  ): TypedContractMethod<[arg0: AddressLike], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'owner',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'pendingOwner',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'quoteAsset',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'renounceOwnership',
  ): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setDistributeEnabled',
  ): TypedContractMethod<[isEnabled: boolean], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'totalOwedQuantity',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'transferOwnership',
  ): TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'withdrawEscrow',
  ): TypedContractMethod<[quantity: BigNumberish], [void], 'nonpayable'>;

  getEvent(
    key: 'AssetsDistributed',
  ): TypedContractEvent<
    AssetsDistributedEvent.InputTuple,
    AssetsDistributedEvent.OutputTuple,
    AssetsDistributedEvent.OutputObject
  >;
  getEvent(
    key: 'EscrowWithdrawn',
  ): TypedContractEvent<
    EscrowWithdrawnEvent.InputTuple,
    EscrowWithdrawnEvent.OutputTuple,
    EscrowWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: 'OwnershipTransferStarted',
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: 'OwnershipTransferred',
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    'AssetsDistributed(address,uint256,uint256)': TypedContractEvent<
      AssetsDistributedEvent.InputTuple,
      AssetsDistributedEvent.OutputTuple,
      AssetsDistributedEvent.OutputObject
    >;
    AssetsDistributed: TypedContractEvent<
      AssetsDistributedEvent.InputTuple,
      AssetsDistributedEvent.OutputTuple,
      AssetsDistributedEvent.OutputObject
    >;

    'EscrowWithdrawn(address,uint256,uint256)': TypedContractEvent<
      EscrowWithdrawnEvent.InputTuple,
      EscrowWithdrawnEvent.OutputTuple,
      EscrowWithdrawnEvent.OutputObject
    >;
    EscrowWithdrawn: TypedContractEvent<
      EscrowWithdrawnEvent.InputTuple,
      EscrowWithdrawnEvent.OutputTuple,
      EscrowWithdrawnEvent.OutputObject
    >;

    'OwnershipTransferStarted(address,address)': TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    'OwnershipTransferred(address,address)': TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
