/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from './common';

export interface ExchangeLoopbackAdapter_v1Interface extends Interface {
  getFunction(
    nameOrSignature:
      | 'acceptOwnership'
      | 'exchange'
      | 'exchangeManagedAccountDepositAdapter'
      | 'isWithdrawEnabled'
      | 'owner'
      | 'pendingOwner'
      | 'quoteAsset'
      | 'renounceOwnership'
      | 'setWithdrawEnabled'
      | 'transferOwnership'
      | 'withdrawQuoteAsset',
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | 'ComposeFailed'
      | 'ComposeSucceeded'
      | 'OwnershipTransferStarted'
      | 'OwnershipTransferred'
      | 'WithdrawQuoteAssetFailed',
  ): EventFragment;

  encodeFunctionData(
    functionFragment: 'acceptOwnership',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'exchange', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'exchangeManagedAccountDepositAdapter',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'isWithdrawEnabled',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'pendingOwner',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'quoteAsset',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'renounceOwnership',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'setWithdrawEnabled',
    values: [boolean],
  ): string;
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'withdrawQuoteAsset',
    values: [AddressLike, BigNumberish, BytesLike],
  ): string;

  decodeFunctionResult(
    functionFragment: 'acceptOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'exchange', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'exchangeManagedAccountDepositAdapter',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'isWithdrawEnabled',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'pendingOwner',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'quoteAsset', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'renounceOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setWithdrawEnabled',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'withdrawQuoteAsset',
    data: BytesLike,
  ): Result;
}

export namespace ComposeFailedEvent {
  export type InputTuple = [
    depositorWallet: AddressLike,
    quantity: BigNumberish,
    errorData: BytesLike,
  ];
  export type OutputTuple = [
    depositorWallet: string,
    quantity: bigint,
    errorData: string,
  ];
  export interface OutputObject {
    depositorWallet: string;
    quantity: bigint;
    errorData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComposeSucceededEvent {
  export type InputTuple = [
    sourceEndpointId: BigNumberish,
    destinationWallet: AddressLike,
    quantity: BigNumberish,
  ];
  export type OutputTuple = [
    sourceEndpointId: bigint,
    destinationWallet: string,
    quantity: bigint,
  ];
  export interface OutputObject {
    sourceEndpointId: bigint;
    destinationWallet: string;
    quantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawQuoteAssetFailedEvent {
  export type InputTuple = [
    depositorWallet: AddressLike,
    quantity: BigNumberish,
    payload: BytesLike,
    errorData: BytesLike,
  ];
  export type OutputTuple = [
    depositorWallet: string,
    quantity: bigint,
    payload: string,
    errorData: string,
  ];
  export interface OutputObject {
    depositorWallet: string;
    quantity: bigint;
    payload: string;
    errorData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ExchangeLoopbackAdapter_v1 extends BaseContract {
  connect(runner?: ContractRunner | null): ExchangeLoopbackAdapter_v1;
  waitForDeployment(): Promise<this>;

  interface: ExchangeLoopbackAdapter_v1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], 'nonpayable'>;

  exchange: TypedContractMethod<[], [string], 'view'>;

  exchangeManagedAccountDepositAdapter: TypedContractMethod<
    [],
    [string],
    'view'
  >;

  isWithdrawEnabled: TypedContractMethod<[], [boolean], 'view'>;

  owner: TypedContractMethod<[], [string], 'view'>;

  pendingOwner: TypedContractMethod<[], [string], 'view'>;

  quoteAsset: TypedContractMethod<[], [string], 'view'>;

  renounceOwnership: TypedContractMethod<[], [void], 'nonpayable'>;

  setWithdrawEnabled: TypedContractMethod<
    [isEnabled: boolean],
    [void],
    'nonpayable'
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    'nonpayable'
  >;

  withdrawQuoteAsset: TypedContractMethod<
    [depositorWallet: AddressLike, quantity: BigNumberish, payload: BytesLike],
    [void],
    'nonpayable'
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: 'acceptOwnership',
  ): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'exchange',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'exchangeManagedAccountDepositAdapter',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'isWithdrawEnabled',
  ): TypedContractMethod<[], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'owner',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'pendingOwner',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'quoteAsset',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'renounceOwnership',
  ): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setWithdrawEnabled',
  ): TypedContractMethod<[isEnabled: boolean], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'transferOwnership',
  ): TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'withdrawQuoteAsset',
  ): TypedContractMethod<
    [depositorWallet: AddressLike, quantity: BigNumberish, payload: BytesLike],
    [void],
    'nonpayable'
  >;

  getEvent(
    key: 'ComposeFailed',
  ): TypedContractEvent<
    ComposeFailedEvent.InputTuple,
    ComposeFailedEvent.OutputTuple,
    ComposeFailedEvent.OutputObject
  >;
  getEvent(
    key: 'ComposeSucceeded',
  ): TypedContractEvent<
    ComposeSucceededEvent.InputTuple,
    ComposeSucceededEvent.OutputTuple,
    ComposeSucceededEvent.OutputObject
  >;
  getEvent(
    key: 'OwnershipTransferStarted',
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: 'OwnershipTransferred',
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: 'WithdrawQuoteAssetFailed',
  ): TypedContractEvent<
    WithdrawQuoteAssetFailedEvent.InputTuple,
    WithdrawQuoteAssetFailedEvent.OutputTuple,
    WithdrawQuoteAssetFailedEvent.OutputObject
  >;

  filters: {
    'ComposeFailed(address,uint256,bytes)': TypedContractEvent<
      ComposeFailedEvent.InputTuple,
      ComposeFailedEvent.OutputTuple,
      ComposeFailedEvent.OutputObject
    >;
    ComposeFailed: TypedContractEvent<
      ComposeFailedEvent.InputTuple,
      ComposeFailedEvent.OutputTuple,
      ComposeFailedEvent.OutputObject
    >;

    'ComposeSucceeded(uint32,address,uint256)': TypedContractEvent<
      ComposeSucceededEvent.InputTuple,
      ComposeSucceededEvent.OutputTuple,
      ComposeSucceededEvent.OutputObject
    >;
    ComposeSucceeded: TypedContractEvent<
      ComposeSucceededEvent.InputTuple,
      ComposeSucceededEvent.OutputTuple,
      ComposeSucceededEvent.OutputObject
    >;

    'OwnershipTransferStarted(address,address)': TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    'OwnershipTransferred(address,address)': TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    'WithdrawQuoteAssetFailed(address,uint256,bytes,bytes)': TypedContractEvent<
      WithdrawQuoteAssetFailedEvent.InputTuple,
      WithdrawQuoteAssetFailedEvent.OutputTuple,
      WithdrawQuoteAssetFailedEvent.OutputObject
    >;
    WithdrawQuoteAssetFailed: TypedContractEvent<
      WithdrawQuoteAssetFailedEvent.InputTuple,
      WithdrawQuoteAssetFailedEvent.OutputTuple,
      WithdrawQuoteAssetFailedEvent.OutputObject
    >;
  };
}
