/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from './common';

export interface ExchangeLayerZeroAdapter_v1Interface extends Interface {
  getFunction(
    nameOrSignature:
      | 'MAX_MINIMUM_WITHDRAW_QUANTITY_MULTIPLIER'
      | 'MIN_MINIMUM_WITHDRAW_QUANTITY_MULTIPLIER'
      | 'acceptOwnership'
      | 'addManagedAccountDepositFeeQuantityInAssetUnits'
      | 'addManagedAccountManagerWalletNativeDropQuantity'
      | 'depositToManagedAccountFeeQuantityInAssetUnits'
      | 'estimateWithdrawQuantityInAssetUnits'
      | 'ethereumEndpointId'
      | 'exchange'
      | 'isDepositEnabled'
      | 'isWithdrawEnabled'
      | 'loadEthereumWithdrawalGasFeeInAssetUnits'
      | 'lzCompose'
      | 'lzEndpoint'
      | 'minimumAddManagedAccountDepositQuantityInAssetUnits'
      | 'minimumDepositToManagedAccountQuantityInAssetUnits'
      | 'minimumWithdrawQuantityMultiplier'
      | 'oft'
      | 'owner'
      | 'pendingOwner'
      | 'quoteAsset'
      | 'renounceOwnership'
      | 'setComposeParameters'
      | 'setDepositEnabled'
      | 'setMinimumWithdrawQuantityMultiplier'
      | 'setStargateForwarder'
      | 'setWithdrawEnabled'
      | 'stargateForwarder'
      | 'transferOwnership'
      | 'withdrawNativeAsset'
      | 'withdrawQuoteAsset',
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | 'ComposeFailed'
      | 'ComposeSucceeded'
      | 'OwnershipTransferStarted'
      | 'OwnershipTransferred'
      | 'WithdrawQuoteAssetFailed',
  ): EventFragment;

  encodeFunctionData(
    functionFragment: 'MAX_MINIMUM_WITHDRAW_QUANTITY_MULTIPLIER',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MIN_MINIMUM_WITHDRAW_QUANTITY_MULTIPLIER',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'acceptOwnership',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'addManagedAccountDepositFeeQuantityInAssetUnits',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'addManagedAccountManagerWalletNativeDropQuantity',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'depositToManagedAccountFeeQuantityInAssetUnits',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'estimateWithdrawQuantityInAssetUnits',
    values: [BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'ethereumEndpointId',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'exchange', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'isDepositEnabled',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'isWithdrawEnabled',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'loadEthereumWithdrawalGasFeeInAssetUnits',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'lzCompose',
    values: [AddressLike, BytesLike, BytesLike, AddressLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'lzEndpoint',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'minimumAddManagedAccountDepositQuantityInAssetUnits',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'minimumDepositToManagedAccountQuantityInAssetUnits',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'minimumWithdrawQuantityMultiplier',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'oft', values?: undefined): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'pendingOwner',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'quoteAsset',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'renounceOwnership',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'setComposeParameters',
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: 'setDepositEnabled',
    values: [boolean],
  ): string;
  encodeFunctionData(
    functionFragment: 'setMinimumWithdrawQuantityMultiplier',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'setStargateForwarder',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'setWithdrawEnabled',
    values: [boolean],
  ): string;
  encodeFunctionData(
    functionFragment: 'stargateForwarder',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'withdrawNativeAsset',
    values: [AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'withdrawQuoteAsset',
    values: [AddressLike, BigNumberish, BytesLike],
  ): string;

  decodeFunctionResult(
    functionFragment: 'MAX_MINIMUM_WITHDRAW_QUANTITY_MULTIPLIER',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MIN_MINIMUM_WITHDRAW_QUANTITY_MULTIPLIER',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'acceptOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'addManagedAccountDepositFeeQuantityInAssetUnits',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'addManagedAccountManagerWalletNativeDropQuantity',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'depositToManagedAccountFeeQuantityInAssetUnits',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'estimateWithdrawQuantityInAssetUnits',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'ethereumEndpointId',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'exchange', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'isDepositEnabled',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'isWithdrawEnabled',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadEthereumWithdrawalGasFeeInAssetUnits',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'lzCompose', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'lzEndpoint', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'minimumAddManagedAccountDepositQuantityInAssetUnits',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'minimumDepositToManagedAccountQuantityInAssetUnits',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'minimumWithdrawQuantityMultiplier',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'oft', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'pendingOwner',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'quoteAsset', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'renounceOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setComposeParameters',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setDepositEnabled',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setMinimumWithdrawQuantityMultiplier',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setStargateForwarder',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setWithdrawEnabled',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'stargateForwarder',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'withdrawNativeAsset',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'withdrawQuoteAsset',
    data: BytesLike,
  ): Result;
}

export namespace ComposeFailedEvent {
  export type InputTuple = [
    depositorWallet: AddressLike,
    quantity: BigNumberish,
    errorData: BytesLike,
  ];
  export type OutputTuple = [
    depositorWallet: string,
    quantity: bigint,
    errorData: string,
  ];
  export interface OutputObject {
    depositorWallet: string;
    quantity: bigint;
    errorData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComposeSucceededEvent {
  export type InputTuple = [
    sourceEndpointId: BigNumberish,
    destinationWallet: AddressLike,
    quantity: BigNumberish,
  ];
  export type OutputTuple = [
    sourceEndpointId: bigint,
    destinationWallet: string,
    quantity: bigint,
  ];
  export interface OutputObject {
    sourceEndpointId: bigint;
    destinationWallet: string;
    quantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawQuoteAssetFailedEvent {
  export type InputTuple = [
    depositorWallet: AddressLike,
    quantity: BigNumberish,
    payload: BytesLike,
    errorData: BytesLike,
  ];
  export type OutputTuple = [
    depositorWallet: string,
    quantity: bigint,
    payload: string,
    errorData: string,
  ];
  export interface OutputObject {
    depositorWallet: string;
    quantity: bigint;
    payload: string;
    errorData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ExchangeLayerZeroAdapter_v1 extends BaseContract {
  connect(runner?: ContractRunner | null): ExchangeLayerZeroAdapter_v1;
  waitForDeployment(): Promise<this>;

  interface: ExchangeLayerZeroAdapter_v1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  MAX_MINIMUM_WITHDRAW_QUANTITY_MULTIPLIER: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  MIN_MINIMUM_WITHDRAW_QUANTITY_MULTIPLIER: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  acceptOwnership: TypedContractMethod<[], [void], 'nonpayable'>;

  addManagedAccountDepositFeeQuantityInAssetUnits: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  addManagedAccountManagerWalletNativeDropQuantity: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  depositToManagedAccountFeeQuantityInAssetUnits: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  estimateWithdrawQuantityInAssetUnits: TypedContractMethod<
    [destinationEndpointId: BigNumberish, quantity: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        estimatedWithdrawQuantityInAssetUnits: bigint;
        minimumWithdrawQuantityInAssetUnits: bigint;
        poolDecimals: bigint;
      },
    ],
    'view'
  >;

  ethereumEndpointId: TypedContractMethod<[], [bigint], 'view'>;

  exchange: TypedContractMethod<[], [string], 'view'>;

  isDepositEnabled: TypedContractMethod<[], [boolean], 'view'>;

  isWithdrawEnabled: TypedContractMethod<[], [boolean], 'view'>;

  loadEthereumWithdrawalGasFeeInAssetUnits: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  lzCompose: TypedContractMethod<
    [
      _from: AddressLike,
      arg1: BytesLike,
      _message: BytesLike,
      arg3: AddressLike,
      arg4: BytesLike,
    ],
    [void],
    'payable'
  >;

  lzEndpoint: TypedContractMethod<[], [string], 'view'>;

  minimumAddManagedAccountDepositQuantityInAssetUnits: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  minimumDepositToManagedAccountQuantityInAssetUnits: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  minimumWithdrawQuantityMultiplier: TypedContractMethod<[], [bigint], 'view'>;

  oft: TypedContractMethod<[], [string], 'view'>;

  owner: TypedContractMethod<[], [string], 'view'>;

  pendingOwner: TypedContractMethod<[], [string], 'view'>;

  quoteAsset: TypedContractMethod<[], [string], 'view'>;

  renounceOwnership: TypedContractMethod<[], [void], 'nonpayable'>;

  setComposeParameters: TypedContractMethod<
    [
      addManagedAccountDepositFeeQuantityInAssetUnits_: BigNumberish,
      addManagedAccountManagerWalletNativeDropQuantity_: BigNumberish,
      depositToManagedAccountFeeQuantityInAssetUnits_: BigNumberish,
      minimumAddManagedAccountDepositQuantityInAssetUnits_: BigNumberish,
      minimumDepositToManagedAccountQuantityInAssetUnits_: BigNumberish,
      minimumWithdrawQuantityMultiplier_: BigNumberish,
    ],
    [void],
    'nonpayable'
  >;

  setDepositEnabled: TypedContractMethod<
    [isEnabled: boolean],
    [void],
    'nonpayable'
  >;

  setMinimumWithdrawQuantityMultiplier: TypedContractMethod<
    [newMinimumWithdrawQuantityMultiplier: BigNumberish],
    [void],
    'nonpayable'
  >;

  setStargateForwarder: TypedContractMethod<
    [stargateForwarder_: AddressLike],
    [void],
    'nonpayable'
  >;

  setWithdrawEnabled: TypedContractMethod<
    [isEnabled: boolean],
    [void],
    'nonpayable'
  >;

  stargateForwarder: TypedContractMethod<[], [string], 'view'>;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    'nonpayable'
  >;

  withdrawNativeAsset: TypedContractMethod<
    [destinationContractOrWallet: AddressLike, quantity: BigNumberish],
    [void],
    'nonpayable'
  >;

  withdrawQuoteAsset: TypedContractMethod<
    [depositorWallet: AddressLike, quantity: BigNumberish, payload: BytesLike],
    [void],
    'nonpayable'
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: 'MAX_MINIMUM_WITHDRAW_QUANTITY_MULTIPLIER',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MIN_MINIMUM_WITHDRAW_QUANTITY_MULTIPLIER',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'acceptOwnership',
  ): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'addManagedAccountDepositFeeQuantityInAssetUnits',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'addManagedAccountManagerWalletNativeDropQuantity',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'depositToManagedAccountFeeQuantityInAssetUnits',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'estimateWithdrawQuantityInAssetUnits',
  ): TypedContractMethod<
    [destinationEndpointId: BigNumberish, quantity: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        estimatedWithdrawQuantityInAssetUnits: bigint;
        minimumWithdrawQuantityInAssetUnits: bigint;
        poolDecimals: bigint;
      },
    ],
    'view'
  >;
  getFunction(
    nameOrSignature: 'ethereumEndpointId',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'exchange',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'isDepositEnabled',
  ): TypedContractMethod<[], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'isWithdrawEnabled',
  ): TypedContractMethod<[], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'loadEthereumWithdrawalGasFeeInAssetUnits',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'lzCompose',
  ): TypedContractMethod<
    [
      _from: AddressLike,
      arg1: BytesLike,
      _message: BytesLike,
      arg3: AddressLike,
      arg4: BytesLike,
    ],
    [void],
    'payable'
  >;
  getFunction(
    nameOrSignature: 'lzEndpoint',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'minimumAddManagedAccountDepositQuantityInAssetUnits',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'minimumDepositToManagedAccountQuantityInAssetUnits',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'minimumWithdrawQuantityMultiplier',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'oft',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'owner',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'pendingOwner',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'quoteAsset',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'renounceOwnership',
  ): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setComposeParameters',
  ): TypedContractMethod<
    [
      addManagedAccountDepositFeeQuantityInAssetUnits_: BigNumberish,
      addManagedAccountManagerWalletNativeDropQuantity_: BigNumberish,
      depositToManagedAccountFeeQuantityInAssetUnits_: BigNumberish,
      minimumAddManagedAccountDepositQuantityInAssetUnits_: BigNumberish,
      minimumDepositToManagedAccountQuantityInAssetUnits_: BigNumberish,
      minimumWithdrawQuantityMultiplier_: BigNumberish,
    ],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'setDepositEnabled',
  ): TypedContractMethod<[isEnabled: boolean], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setMinimumWithdrawQuantityMultiplier',
  ): TypedContractMethod<
    [newMinimumWithdrawQuantityMultiplier: BigNumberish],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'setStargateForwarder',
  ): TypedContractMethod<
    [stargateForwarder_: AddressLike],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'setWithdrawEnabled',
  ): TypedContractMethod<[isEnabled: boolean], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'stargateForwarder',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'transferOwnership',
  ): TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'withdrawNativeAsset',
  ): TypedContractMethod<
    [destinationContractOrWallet: AddressLike, quantity: BigNumberish],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'withdrawQuoteAsset',
  ): TypedContractMethod<
    [depositorWallet: AddressLike, quantity: BigNumberish, payload: BytesLike],
    [void],
    'nonpayable'
  >;

  getEvent(
    key: 'ComposeFailed',
  ): TypedContractEvent<
    ComposeFailedEvent.InputTuple,
    ComposeFailedEvent.OutputTuple,
    ComposeFailedEvent.OutputObject
  >;
  getEvent(
    key: 'ComposeSucceeded',
  ): TypedContractEvent<
    ComposeSucceededEvent.InputTuple,
    ComposeSucceededEvent.OutputTuple,
    ComposeSucceededEvent.OutputObject
  >;
  getEvent(
    key: 'OwnershipTransferStarted',
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: 'OwnershipTransferred',
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: 'WithdrawQuoteAssetFailed',
  ): TypedContractEvent<
    WithdrawQuoteAssetFailedEvent.InputTuple,
    WithdrawQuoteAssetFailedEvent.OutputTuple,
    WithdrawQuoteAssetFailedEvent.OutputObject
  >;

  filters: {
    'ComposeFailed(address,uint256,bytes)': TypedContractEvent<
      ComposeFailedEvent.InputTuple,
      ComposeFailedEvent.OutputTuple,
      ComposeFailedEvent.OutputObject
    >;
    ComposeFailed: TypedContractEvent<
      ComposeFailedEvent.InputTuple,
      ComposeFailedEvent.OutputTuple,
      ComposeFailedEvent.OutputObject
    >;

    'ComposeSucceeded(uint32,address,uint256)': TypedContractEvent<
      ComposeSucceededEvent.InputTuple,
      ComposeSucceededEvent.OutputTuple,
      ComposeSucceededEvent.OutputObject
    >;
    ComposeSucceeded: TypedContractEvent<
      ComposeSucceededEvent.InputTuple,
      ComposeSucceededEvent.OutputTuple,
      ComposeSucceededEvent.OutputObject
    >;

    'OwnershipTransferStarted(address,address)': TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    'OwnershipTransferred(address,address)': TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    'WithdrawQuoteAssetFailed(address,uint256,bytes,bytes)': TypedContractEvent<
      WithdrawQuoteAssetFailedEvent.InputTuple,
      WithdrawQuoteAssetFailedEvent.OutputTuple,
      WithdrawQuoteAssetFailedEvent.OutputObject
    >;
    WithdrawQuoteAssetFailed: TypedContractEvent<
      WithdrawQuoteAssetFailedEvent.InputTuple,
      WithdrawQuoteAssetFailedEvent.OutputTuple,
      WithdrawQuoteAssetFailedEvent.OutputObject
    >;
  };
}
