/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from './common';

export type LoadVaultDepositorsResultStruct = {
  costBasis: BigNumberish;
  initialDepositTimestampInS: BigNumberish;
  owedQuantity: BigNumberish;
};

export type LoadVaultDepositorsResultStructOutput = [
  costBasis: bigint,
  initialDepositTimestampInS: bigint,
  owedQuantity: bigint,
] & {
  costBasis: bigint;
  initialDepositTimestampInS: bigint;
  owedQuantity: bigint;
};

export type VaultWithdrawQueueItemStruct = {
  nonce: BigNumberish;
  depositorWallet: AddressLike;
  grossQuantity: BigNumberish;
};

export type VaultWithdrawQueueItemStructOutput = [
  nonce: bigint,
  depositorWallet: string,
  grossQuantity: bigint,
] & { nonce: bigint; depositorWallet: string; grossQuantity: bigint };

export declare namespace FixedIncomeVaultProvider_v1 {
  export type VaultConfigurationFieldsStruct = {
    managerWallet: AddressLike;
    effectiveTimestampInS: BigNumberish;
    interestMultiplier: BigNumberish;
    maximumNetDeposits: BigNumberish;
    maximumTotalOwedQuantityAvailableMultiplierToInitiateExit: BigNumberish;
    minimumTotalOwedQuantityAvailableMultiplierToAllowManagerWalletWithdrawal: BigNumberish;
    minimumUnappliedWithdrawalAgeInSToInitiateExit: BigNumberish;
    withdrawalLimitPercentForDepositors: BigNumberish;
    withdrawalLimitPercentForVault: BigNumberish;
  };

  export type VaultConfigurationFieldsStructOutput = [
    managerWallet: string,
    effectiveTimestampInS: bigint,
    interestMultiplier: bigint,
    maximumNetDeposits: bigint,
    maximumTotalOwedQuantityAvailableMultiplierToInitiateExit: bigint,
    minimumTotalOwedQuantityAvailableMultiplierToAllowManagerWalletWithdrawal: bigint,
    minimumUnappliedWithdrawalAgeInSToInitiateExit: bigint,
    withdrawalLimitPercentForDepositors: bigint,
    withdrawalLimitPercentForVault: bigint,
  ] & {
    managerWallet: string;
    effectiveTimestampInS: bigint;
    interestMultiplier: bigint;
    maximumNetDeposits: bigint;
    maximumTotalOwedQuantityAvailableMultiplierToInitiateExit: bigint;
    minimumTotalOwedQuantityAvailableMultiplierToAllowManagerWalletWithdrawal: bigint;
    minimumUnappliedWithdrawalAgeInSToInitiateExit: bigint;
    withdrawalLimitPercentForDepositors: bigint;
    withdrawalLimitPercentForVault: bigint;
  };
}

export interface FixedIncomeVaultProviderStateAggregator_v1Interface
  extends Interface {
  getFunction(
    nameOrSignature:
      | 'fixedIncomeVaultProvider'
      | 'loadTotalQuantitiesOwedByVaults'
      | 'loadVaultConfigurations'
      | 'loadVaultDepositorsByDepositorWallet'
      | 'loadVaultDepositorsByManagerWallet'
      | 'loadVaultWithdrawalQueue',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'fixedIncomeVaultProvider',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'loadTotalQuantitiesOwedByVaults',
    values: [AddressLike[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultConfigurations',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultDepositorsByDepositorWallet',
    values: [AddressLike[], AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultDepositorsByManagerWallet',
    values: [AddressLike, AddressLike[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultWithdrawalQueue',
    values: [AddressLike],
  ): string;

  decodeFunctionResult(
    functionFragment: 'fixedIncomeVaultProvider',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadTotalQuantitiesOwedByVaults',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultConfigurations',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultDepositorsByDepositorWallet',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultDepositorsByManagerWallet',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultWithdrawalQueue',
    data: BytesLike,
  ): Result;
}

export interface FixedIncomeVaultProviderStateAggregator_v1
  extends BaseContract {
  connect(
    runner?: ContractRunner | null,
  ): FixedIncomeVaultProviderStateAggregator_v1;
  waitForDeployment(): Promise<this>;

  interface: FixedIncomeVaultProviderStateAggregator_v1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  fixedIncomeVaultProvider: TypedContractMethod<[], [string], 'view'>;

  loadTotalQuantitiesOwedByVaults: TypedContractMethod<
    [managerWallets: AddressLike[]],
    [bigint[]],
    'view'
  >;

  loadVaultConfigurations: TypedContractMethod<
    [managerWallet: AddressLike],
    [FixedIncomeVaultProvider_v1.VaultConfigurationFieldsStructOutput[]],
    'view'
  >;

  loadVaultDepositorsByDepositorWallet: TypedContractMethod<
    [managerWallets: AddressLike[], wallet: AddressLike],
    [LoadVaultDepositorsResultStructOutput[]],
    'view'
  >;

  loadVaultDepositorsByManagerWallet: TypedContractMethod<
    [managerWallet: AddressLike, wallets: AddressLike[]],
    [LoadVaultDepositorsResultStructOutput[]],
    'view'
  >;

  loadVaultWithdrawalQueue: TypedContractMethod<
    [managerWallet: AddressLike],
    [VaultWithdrawQueueItemStructOutput[]],
    'view'
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: 'fixedIncomeVaultProvider',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'loadTotalQuantitiesOwedByVaults',
  ): TypedContractMethod<[managerWallets: AddressLike[]], [bigint[]], 'view'>;
  getFunction(
    nameOrSignature: 'loadVaultConfigurations',
  ): TypedContractMethod<
    [managerWallet: AddressLike],
    [FixedIncomeVaultProvider_v1.VaultConfigurationFieldsStructOutput[]],
    'view'
  >;
  getFunction(
    nameOrSignature: 'loadVaultDepositorsByDepositorWallet',
  ): TypedContractMethod<
    [managerWallets: AddressLike[], wallet: AddressLike],
    [LoadVaultDepositorsResultStructOutput[]],
    'view'
  >;
  getFunction(
    nameOrSignature: 'loadVaultDepositorsByManagerWallet',
  ): TypedContractMethod<
    [managerWallet: AddressLike, wallets: AddressLike[]],
    [LoadVaultDepositorsResultStructOutput[]],
    'view'
  >;
  getFunction(
    nameOrSignature: 'loadVaultWithdrawalQueue',
  ): TypedContractMethod<
    [managerWallet: AddressLike],
    [VaultWithdrawQueueItemStructOutput[]],
    'view'
  >;

  filters: {};
}
