/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from './common';

export type WithdrawalFromManagedAccountByQuantityStruct = {
  nonce: BigNumberish;
  managerWallet: AddressLike;
  depositorWallet: AddressLike;
  grossQuantity: BigNumberish;
  maxShares: BigNumberish;
  maximumGasFee: BigNumberish;
  managedAccountProvider: AddressLike;
  managedAccountProviderPayload: BytesLike;
  bridgeAdapter: AddressLike;
  bridgeAdapterPayload: BytesLike;
  gasFee: BigNumberish;
  walletSignature: BytesLike;
};

export type WithdrawalFromManagedAccountByQuantityStructOutput = [
  nonce: bigint,
  managerWallet: string,
  depositorWallet: string,
  grossQuantity: bigint,
  maxShares: bigint,
  maximumGasFee: bigint,
  managedAccountProvider: string,
  managedAccountProviderPayload: string,
  bridgeAdapter: string,
  bridgeAdapterPayload: string,
  gasFee: bigint,
  walletSignature: string,
] & {
  nonce: bigint;
  managerWallet: string;
  depositorWallet: string;
  grossQuantity: bigint;
  maxShares: bigint;
  maximumGasFee: bigint;
  managedAccountProvider: string;
  managedAccountProviderPayload: string;
  bridgeAdapter: string;
  bridgeAdapterPayload: string;
  gasFee: bigint;
  walletSignature: string;
};

export type WithdrawalFromManagedAccountBySharesStruct = {
  nonce: BigNumberish;
  managerWallet: AddressLike;
  depositorWallet: AddressLike;
  shares: BigNumberish;
  minimumQuantity: BigNumberish;
  maximumGasFee: BigNumberish;
  managedAccountProvider: AddressLike;
  managedAccountProviderPayload: BytesLike;
  bridgeAdapter: AddressLike;
  bridgeAdapterPayload: BytesLike;
  gasFee: BigNumberish;
  grossQuantity: BigNumberish;
  walletSignature: BytesLike;
};

export type WithdrawalFromManagedAccountBySharesStructOutput = [
  nonce: bigint,
  managerWallet: string,
  depositorWallet: string,
  shares: bigint,
  minimumQuantity: bigint,
  maximumGasFee: bigint,
  managedAccountProvider: string,
  managedAccountProviderPayload: string,
  bridgeAdapter: string,
  bridgeAdapterPayload: string,
  gasFee: bigint,
  grossQuantity: bigint,
  walletSignature: string,
] & {
  nonce: bigint;
  managerWallet: string;
  depositorWallet: string;
  shares: bigint;
  minimumQuantity: bigint;
  maximumGasFee: bigint;
  managedAccountProvider: string;
  managedAccountProviderPayload: string;
  bridgeAdapter: string;
  bridgeAdapterPayload: string;
  gasFee: bigint;
  grossQuantity: bigint;
  walletSignature: string;
};

export type WithdrawalFromManagedAccountStruct = {
  withdrawalType: BigNumberish;
  withdrawalByQuantity: WithdrawalFromManagedAccountByQuantityStruct;
  withdrawalByShares: WithdrawalFromManagedAccountBySharesStruct;
};

export type WithdrawalFromManagedAccountStructOutput = [
  withdrawalType: bigint,
  withdrawalByQuantity: WithdrawalFromManagedAccountByQuantityStructOutput,
  withdrawalByShares: WithdrawalFromManagedAccountBySharesStructOutput,
] & {
  withdrawalType: bigint;
  withdrawalByQuantity: WithdrawalFromManagedAccountByQuantityStructOutput;
  withdrawalByShares: WithdrawalFromManagedAccountBySharesStructOutput;
};

export declare namespace FixedIncomeVaultProvider_v1 {
  export type VaultBalanceForWalletSummaryStruct = {
    costBasis: BigNumberish;
    initialDepositTimestampInS: BigNumberish;
    lockedQuantity: BigNumberish;
    owedQuantity: BigNumberish;
    pendingDepositQuantity: BigNumberish;
    quantityAvailableToWithdraw: BigNumberish;
    withdrawalLimitWindowEndTimestampInS: BigNumberish;
  };

  export type VaultBalanceForWalletSummaryStructOutput = [
    costBasis: bigint,
    initialDepositTimestampInS: bigint,
    lockedQuantity: bigint,
    owedQuantity: bigint,
    pendingDepositQuantity: bigint,
    quantityAvailableToWithdraw: bigint,
    withdrawalLimitWindowEndTimestampInS: bigint,
  ] & {
    costBasis: bigint;
    initialDepositTimestampInS: bigint;
    lockedQuantity: bigint;
    owedQuantity: bigint;
    pendingDepositQuantity: bigint;
    quantityAvailableToWithdraw: bigint;
    withdrawalLimitWindowEndTimestampInS: bigint;
  };

  export type VaultConfigurationFieldsStruct = {
    managerWallet: AddressLike;
    effectiveTimestampInS: BigNumberish;
    interestMultiplier: BigNumberish;
    maximumNetDeposits: BigNumberish;
    maximumTotalOwedQuantityAvailableMultiplierToInitiateExit: BigNumberish;
    minimumTotalOwedQuantityAvailableMultiplierToAllowManagerWalletWithdrawal: BigNumberish;
    minimumUnappliedDepositOrWithdrawalAgeInSToInitiateExit: BigNumberish;
    withdrawalLimitPercentForDepositors: BigNumberish;
    withdrawalLimitPercentForVault: BigNumberish;
  };

  export type VaultConfigurationFieldsStructOutput = [
    managerWallet: string,
    effectiveTimestampInS: bigint,
    interestMultiplier: bigint,
    maximumNetDeposits: bigint,
    maximumTotalOwedQuantityAvailableMultiplierToInitiateExit: bigint,
    minimumTotalOwedQuantityAvailableMultiplierToAllowManagerWalletWithdrawal: bigint,
    minimumUnappliedDepositOrWithdrawalAgeInSToInitiateExit: bigint,
    withdrawalLimitPercentForDepositors: bigint,
    withdrawalLimitPercentForVault: bigint,
  ] & {
    managerWallet: string;
    effectiveTimestampInS: bigint;
    interestMultiplier: bigint;
    maximumNetDeposits: bigint;
    maximumTotalOwedQuantityAvailableMultiplierToInitiateExit: bigint;
    minimumTotalOwedQuantityAvailableMultiplierToAllowManagerWalletWithdrawal: bigint;
    minimumUnappliedDepositOrWithdrawalAgeInSToInitiateExit: bigint;
    withdrawalLimitPercentForDepositors: bigint;
    withdrawalLimitPercentForVault: bigint;
  };

  export type VaultSummaryStruct = {
    isDepositEnabled: boolean;
    isExited: boolean;
    isLiquidated: boolean;
    didManagerWalletWithdrawExit: boolean;
    exitedAccountValue: BigNumberish;
    exitedAtTimestampInS: BigNumberish;
    exitedDepositorPendingDepositQuantity: BigNumberish;
    exitedTotalOwedQuantity: BigNumberish;
    managerLockedQuantity: BigNumberish;
    depositorNetDeposits: BigNumberish;
    numDepositorWallets: BigNumberish;
    totalLockedQuantity: BigNumberish;
    totalOwedQuantity: BigNumberish;
    depositorPendingDepositQuantity: BigNumberish;
    configurationFields: FixedIncomeVaultProvider_v1.VaultConfigurationFieldsStruct;
  };

  export type VaultSummaryStructOutput = [
    isDepositEnabled: boolean,
    isExited: boolean,
    isLiquidated: boolean,
    didManagerWalletWithdrawExit: boolean,
    exitedAccountValue: bigint,
    exitedAtTimestampInS: bigint,
    exitedDepositorPendingDepositQuantity: bigint,
    exitedTotalOwedQuantity: bigint,
    managerLockedQuantity: bigint,
    depositorNetDeposits: bigint,
    numDepositorWallets: bigint,
    totalLockedQuantity: bigint,
    totalOwedQuantity: bigint,
    depositorPendingDepositQuantity: bigint,
    configurationFields: FixedIncomeVaultProvider_v1.VaultConfigurationFieldsStructOutput,
  ] & {
    isDepositEnabled: boolean;
    isExited: boolean;
    isLiquidated: boolean;
    didManagerWalletWithdrawExit: boolean;
    exitedAccountValue: bigint;
    exitedAtTimestampInS: bigint;
    exitedDepositorPendingDepositQuantity: bigint;
    exitedTotalOwedQuantity: bigint;
    managerLockedQuantity: bigint;
    depositorNetDeposits: bigint;
    numDepositorWallets: bigint;
    totalLockedQuantity: bigint;
    totalOwedQuantity: bigint;
    depositorPendingDepositQuantity: bigint;
    configurationFields: FixedIncomeVaultProvider_v1.VaultConfigurationFieldsStructOutput;
  };
}

export declare namespace VaultDepositQueue {
  export type ItemStruct = {
    index: BigNumberish;
    quantity: BigNumberish;
    sourceWallet: AddressLike;
    depositorWallet: AddressLike;
    managerWallet: AddressLike;
    managedAccount: AddressLike;
    payload: BytesLike;
    addedToQueueAtTimestampInS: BigNumberish;
  };

  export type ItemStructOutput = [
    index: bigint,
    quantity: bigint,
    sourceWallet: string,
    depositorWallet: string,
    managerWallet: string,
    managedAccount: string,
    payload: string,
    addedToQueueAtTimestampInS: bigint,
  ] & {
    index: bigint;
    quantity: bigint;
    sourceWallet: string;
    depositorWallet: string;
    managerWallet: string;
    managedAccount: string;
    payload: string;
    addedToQueueAtTimestampInS: bigint;
  };
}

export interface FixedIncomeVaultProvider_v1Interface extends Interface {
  getFunction(
    nameOrSignature:
      | 'INTEREST_PERIOD_IN_S'
      | 'MAX_INTEREST_MULTIPLIER'
      | 'MAX_MANAGED_ACCOUNT_UPGRADE_BLOCK_TIMESTAMP_DELAY_IN_S'
      | 'MAX_MAXIMUM_NET_DEPOSITS'
      | 'MAX_MAXIMUM_TOTAL_OWED_QUANTITY_AVAILABLE_MULTIPLIER_TO_INITIATE_EXIT'
      | 'MAX_MINIMUM_TOTAL_OWED_QUANTITY_AVAILABLE_MULTIPLIER_TO_ALLOW_MANAGER_WALLET_WITHDRAWAL'
      | 'MAX_MINIMUM_UNAPPLIED_DEPOSIT_OR_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT'
      | 'MAX_WITHDRAWAL_LIMIT_PERCENT_FOR_DEPOSITORS'
      | 'MAX_WITHDRAWAL_LIMIT_PERCENT_FOR_VAULT'
      | 'MAX_WITHDRAWAL_LIMIT_WINDOW_SIZE_IN_S'
      | 'MINIMUM_WITHDRAWAL_MAXIMUM_GAS_FEE'
      | 'MIN_INTEREST_MULTIPLIER'
      | 'MIN_MANAGED_ACCOUNT_UPGRADE_BLOCK_TIMESTAMP_DELAY_IN_S'
      | 'MIN_MAXIMUM_NET_DEPOSITS'
      | 'MIN_MAXIMUM_TOTAL_OWED_QUANTITY_AVAILABLE_MULTIPLIER_TO_INITIATE_EXIT'
      | 'MIN_MINIMUM_TOTAL_OWED_QUANTITY_AVAILABLE_MULTIPLIER_TO_ALLOW_MANAGER_WALLET_WITHDRAWAL'
      | 'MIN_MINIMUM_UNAPPLIED_DEPOSIT_OR_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT'
      | 'MIN_WITHDRAWAL_LIMIT_PERCENT_FOR_DEPOSITORS'
      | 'MIN_WITHDRAWAL_LIMIT_PERCENT_FOR_VAULT'
      | 'MIN_WITHDRAWAL_LIMIT_WINDOW_SIZE_IN_S'
      | 'addManagedAccount'
      | 'adminWallet'
      | 'applyPendingDeposit'
      | 'applyPendingWithdrawal'
      | 'cancelManagedAccountUpgrade'
      | 'cancelPendingWithdrawal'
      | 'custodian'
      | 'deposit'
      | 'emitEventsForFrontOfDepositAndWithdrawalQueues'
      | 'exitWallet'
      | 'finalizeManagedAccountUpgrade'
      | 'initiateManagedAccountUpgrade'
      | 'intervalTick'
      | 'isAddManagedAccountEnabled'
      | 'isApplyDepositEnabled'
      | 'isDepositEnabled'
      | 'liquidateManagerWallet'
      | 'loadVaultBalanceForWalletSummary'
      | 'loadVaultConfiguration'
      | 'loadVaultConfigurationsLength'
      | 'loadVaultDepositQueueItem'
      | 'loadVaultDepositQueueLength'
      | 'loadVaultSummary'
      | 'loadVaultWithdrawQueueItem'
      | 'loadVaultWithdrawQueueLength'
      | 'managedAccountUpgradeBlockTimestampDelayInS'
      | 'ownerWallet'
      | 'removeAdmin'
      | 'removeOwner'
      | 'seenDepositIndexes'
      | 'seenWithdrawalHashes'
      | 'setAddManagedAccountEnabledAdmin'
      | 'setAdmin'
      | 'setDepositEnabled'
      | 'setDepositEnabledAdmin'
      | 'setManagedAccountUpgradeBlockTimestampDelay'
      | 'setOwner'
      | 'setWithdrawalDispatcher'
      | 'skim'
      | 'vaultConfigurationUpgradesByManagerWallet'
      | 'withdrawByQuantity'
      | 'withdrawByShares'
      | 'withdrawExit'
      | 'withdrawalDispatcherWallet'
      | 'withdrawalLimitWindowSizeInS',
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | 'AddManagedAccountsDisabledAdmin'
      | 'AddManagedAccountsEnabledAdmin'
      | 'DepositToManagedAccountApplied'
      | 'DepositToManagedAccountReadyToApply'
      | 'DepositsDisabled'
      | 'DepositsDisabledAdmin'
      | 'DepositsEnabled'
      | 'DepositsEnabledAdmin'
      | 'LiquidatedVaultPendingDepositRefundFailed'
      | 'ManagedAccountAdded'
      | 'ManagedAccountUpgradeBlockTimestampDelayChanged'
      | 'ManagedAccountUpgradeCanceled'
      | 'ManagedAccountUpgradeFinalized'
      | 'ManagedAccountUpgradeInitiated'
      | 'ManagerWalletLiquidated'
      | 'WithdrawalDispatcherChanged'
      | 'WithdrawalFromManagedAccountApplied'
      | 'WithdrawalFromManagedAccountCanceled'
      | 'WithdrawalFromManagedAccountReadyToApply',
  ): EventFragment;

  encodeFunctionData(
    functionFragment: 'INTEREST_PERIOD_IN_S',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MAX_INTEREST_MULTIPLIER',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MAX_MANAGED_ACCOUNT_UPGRADE_BLOCK_TIMESTAMP_DELAY_IN_S',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MAX_MAXIMUM_NET_DEPOSITS',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MAX_MAXIMUM_TOTAL_OWED_QUANTITY_AVAILABLE_MULTIPLIER_TO_INITIATE_EXIT',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MAX_MINIMUM_TOTAL_OWED_QUANTITY_AVAILABLE_MULTIPLIER_TO_ALLOW_MANAGER_WALLET_WITHDRAWAL',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MAX_MINIMUM_UNAPPLIED_DEPOSIT_OR_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MAX_WITHDRAWAL_LIMIT_PERCENT_FOR_DEPOSITORS',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MAX_WITHDRAWAL_LIMIT_PERCENT_FOR_VAULT',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MAX_WITHDRAWAL_LIMIT_WINDOW_SIZE_IN_S',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MINIMUM_WITHDRAWAL_MAXIMUM_GAS_FEE',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MIN_INTEREST_MULTIPLIER',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MIN_MANAGED_ACCOUNT_UPGRADE_BLOCK_TIMESTAMP_DELAY_IN_S',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MIN_MAXIMUM_NET_DEPOSITS',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MIN_MAXIMUM_TOTAL_OWED_QUANTITY_AVAILABLE_MULTIPLIER_TO_INITIATE_EXIT',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MIN_MINIMUM_TOTAL_OWED_QUANTITY_AVAILABLE_MULTIPLIER_TO_ALLOW_MANAGER_WALLET_WITHDRAWAL',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MIN_MINIMUM_UNAPPLIED_DEPOSIT_OR_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MIN_WITHDRAWAL_LIMIT_PERCENT_FOR_DEPOSITORS',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MIN_WITHDRAWAL_LIMIT_PERCENT_FOR_VAULT',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MIN_WITHDRAWAL_LIMIT_WINDOW_SIZE_IN_S',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'addManagedAccount',
    values: [AddressLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'adminWallet',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'applyPendingDeposit',
    values: [BigNumberish, AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'applyPendingWithdrawal',
    values: [BigNumberish, BigNumberish, AddressLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'cancelManagedAccountUpgrade',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'cancelPendingWithdrawal',
    values: [BigNumberish, AddressLike, BytesLike],
  ): string;
  encodeFunctionData(functionFragment: 'custodian', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'deposit',
    values: [
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: 'emitEventsForFrontOfDepositAndWithdrawalQueues',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'exitWallet',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'finalizeManagedAccountUpgrade',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'initiateManagedAccountUpgrade',
    values: [BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'intervalTick',
    values: [BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'isAddManagedAccountEnabled',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'isApplyDepositEnabled',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'isDepositEnabled',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'liquidateManagerWallet',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultBalanceForWalletSummary',
    values: [AddressLike, AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultConfiguration',
    values: [AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultConfigurationsLength',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultDepositQueueItem',
    values: [AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultDepositQueueLength',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultSummary',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultWithdrawQueueItem',
    values: [AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultWithdrawQueueLength',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'managedAccountUpgradeBlockTimestampDelayInS',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'ownerWallet',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'removeAdmin',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'removeOwner',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'seenDepositIndexes',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'seenWithdrawalHashes',
    values: [BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'setAddManagedAccountEnabledAdmin',
    values: [boolean],
  ): string;
  encodeFunctionData(
    functionFragment: 'setAdmin',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'setDepositEnabled',
    values: [boolean],
  ): string;
  encodeFunctionData(
    functionFragment: 'setDepositEnabledAdmin',
    values: [boolean, boolean],
  ): string;
  encodeFunctionData(
    functionFragment: 'setManagedAccountUpgradeBlockTimestampDelay',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'setOwner',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'setWithdrawalDispatcher',
    values: [AddressLike],
  ): string;
  encodeFunctionData(functionFragment: 'skim', values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: 'vaultConfigurationUpgradesByManagerWallet',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'withdrawByQuantity',
    values: [WithdrawalFromManagedAccountByQuantityStruct],
  ): string;
  encodeFunctionData(
    functionFragment: 'withdrawByShares',
    values: [WithdrawalFromManagedAccountBySharesStruct],
  ): string;
  encodeFunctionData(
    functionFragment: 'withdrawExit',
    values: [AddressLike, AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'withdrawalDispatcherWallet',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'withdrawalLimitWindowSizeInS',
    values?: undefined,
  ): string;

  decodeFunctionResult(
    functionFragment: 'INTEREST_PERIOD_IN_S',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MAX_INTEREST_MULTIPLIER',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MAX_MANAGED_ACCOUNT_UPGRADE_BLOCK_TIMESTAMP_DELAY_IN_S',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MAX_MAXIMUM_NET_DEPOSITS',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MAX_MAXIMUM_TOTAL_OWED_QUANTITY_AVAILABLE_MULTIPLIER_TO_INITIATE_EXIT',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MAX_MINIMUM_TOTAL_OWED_QUANTITY_AVAILABLE_MULTIPLIER_TO_ALLOW_MANAGER_WALLET_WITHDRAWAL',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MAX_MINIMUM_UNAPPLIED_DEPOSIT_OR_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MAX_WITHDRAWAL_LIMIT_PERCENT_FOR_DEPOSITORS',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MAX_WITHDRAWAL_LIMIT_PERCENT_FOR_VAULT',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MAX_WITHDRAWAL_LIMIT_WINDOW_SIZE_IN_S',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MINIMUM_WITHDRAWAL_MAXIMUM_GAS_FEE',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MIN_INTEREST_MULTIPLIER',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MIN_MANAGED_ACCOUNT_UPGRADE_BLOCK_TIMESTAMP_DELAY_IN_S',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MIN_MAXIMUM_NET_DEPOSITS',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MIN_MAXIMUM_TOTAL_OWED_QUANTITY_AVAILABLE_MULTIPLIER_TO_INITIATE_EXIT',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MIN_MINIMUM_TOTAL_OWED_QUANTITY_AVAILABLE_MULTIPLIER_TO_ALLOW_MANAGER_WALLET_WITHDRAWAL',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MIN_MINIMUM_UNAPPLIED_DEPOSIT_OR_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MIN_WITHDRAWAL_LIMIT_PERCENT_FOR_DEPOSITORS',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MIN_WITHDRAWAL_LIMIT_PERCENT_FOR_VAULT',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MIN_WITHDRAWAL_LIMIT_WINDOW_SIZE_IN_S',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'addManagedAccount',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'adminWallet',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'applyPendingDeposit',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'applyPendingWithdrawal',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'cancelManagedAccountUpgrade',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'cancelPendingWithdrawal',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'custodian', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'emitEventsForFrontOfDepositAndWithdrawalQueues',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'exitWallet', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'finalizeManagedAccountUpgrade',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'initiateManagedAccountUpgrade',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'intervalTick',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'isAddManagedAccountEnabled',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'isApplyDepositEnabled',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'isDepositEnabled',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'liquidateManagerWallet',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultBalanceForWalletSummary',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultConfiguration',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultConfigurationsLength',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultDepositQueueItem',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultDepositQueueLength',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultSummary',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultWithdrawQueueItem',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultWithdrawQueueLength',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'managedAccountUpgradeBlockTimestampDelayInS',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'ownerWallet',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'removeAdmin',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'removeOwner',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'seenDepositIndexes',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'seenWithdrawalHashes',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setAddManagedAccountEnabledAdmin',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'setAdmin', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'setDepositEnabled',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setDepositEnabledAdmin',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setManagedAccountUpgradeBlockTimestampDelay',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'setOwner', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'setWithdrawalDispatcher',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'skim', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'vaultConfigurationUpgradesByManagerWallet',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'withdrawByQuantity',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'withdrawByShares',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'withdrawExit',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'withdrawalDispatcherWallet',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'withdrawalLimitWindowSizeInS',
    data: BytesLike,
  ): Result;
}

export namespace AddManagedAccountsDisabledAdminEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AddManagedAccountsEnabledAdminEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositToManagedAccountAppliedEvent {
  export type InputTuple = [
    managerWallet: AddressLike,
    depositorWallet: AddressLike,
    quantity: BigNumberish,
    newWalletOwedQuantity: BigNumberish,
    newVaultTotalOwedQuantity: BigNumberish,
  ];
  export type OutputTuple = [
    managerWallet: string,
    depositorWallet: string,
    quantity: bigint,
    newWalletOwedQuantity: bigint,
    newVaultTotalOwedQuantity: bigint,
  ];
  export interface OutputObject {
    managerWallet: string;
    depositorWallet: string;
    quantity: bigint;
    newWalletOwedQuantity: bigint;
    newVaultTotalOwedQuantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositToManagedAccountReadyToApplyEvent {
  export type InputTuple = [
    depositIndex: BigNumberish,
    quantity: BigNumberish,
    sourceWallet: AddressLike,
    depositorWallet: AddressLike,
    managerWallet: AddressLike,
  ];
  export type OutputTuple = [
    depositIndex: bigint,
    quantity: bigint,
    sourceWallet: string,
    depositorWallet: string,
    managerWallet: string,
  ];
  export interface OutputObject {
    depositIndex: bigint;
    quantity: bigint;
    sourceWallet: string;
    depositorWallet: string;
    managerWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositsDisabledEvent {
  export type InputTuple = [managerWallet: AddressLike];
  export type OutputTuple = [managerWallet: string];
  export interface OutputObject {
    managerWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositsDisabledAdminEvent {
  export type InputTuple = [
    isDepositEnabled: boolean,
    isApplyDepositEnabled: boolean,
  ];
  export type OutputTuple = [
    isDepositEnabled: boolean,
    isApplyDepositEnabled: boolean,
  ];
  export interface OutputObject {
    isDepositEnabled: boolean;
    isApplyDepositEnabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositsEnabledEvent {
  export type InputTuple = [managerWallet: AddressLike];
  export type OutputTuple = [managerWallet: string];
  export interface OutputObject {
    managerWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositsEnabledAdminEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidatedVaultPendingDepositRefundFailedEvent {
  export type InputTuple = [
    depositorWallet: AddressLike,
    quantityInAssetUnits: BigNumberish,
    depositErrorData: BytesLike,
  ];
  export type OutputTuple = [
    depositorWallet: string,
    quantityInAssetUnits: bigint,
    depositErrorData: string,
  ];
  export interface OutputObject {
    depositorWallet: string;
    quantityInAssetUnits: bigint;
    depositErrorData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagedAccountAddedEvent {
  export type InputTuple = [managerWallet: AddressLike];
  export type OutputTuple = [managerWallet: string];
  export interface OutputObject {
    managerWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagedAccountUpgradeBlockTimestampDelayChangedEvent {
  export type InputTuple = [
    previousValue: BigNumberish,
    newValue: BigNumberish,
  ];
  export type OutputTuple = [previousValue: bigint, newValue: bigint];
  export interface OutputObject {
    previousValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagedAccountUpgradeCanceledEvent {
  export type InputTuple = [managerWallet: AddressLike];
  export type OutputTuple = [managerWallet: string];
  export interface OutputObject {
    managerWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagedAccountUpgradeFinalizedEvent {
  export type InputTuple = [managerWallet: AddressLike];
  export type OutputTuple = [managerWallet: string];
  export interface OutputObject {
    managerWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagedAccountUpgradeInitiatedEvent {
  export type InputTuple = [
    managerWallet: AddressLike,
    blockTimestampThreshold: BigNumberish,
  ];
  export type OutputTuple = [
    managerWallet: string,
    blockTimestampThreshold: bigint,
  ];
  export interface OutputObject {
    managerWallet: string;
    blockTimestampThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagerWalletLiquidatedEvent {
  export type InputTuple = [managerWallet: AddressLike];
  export type OutputTuple = [managerWallet: string];
  export interface OutputObject {
    managerWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalDispatcherChangedEvent {
  export type InputTuple = [previousValue: AddressLike, newValue: AddressLike];
  export type OutputTuple = [previousValue: string, newValue: string];
  export interface OutputObject {
    previousValue: string;
    newValue: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalFromManagedAccountAppliedEvent {
  export type InputTuple = [
    managerWallet: AddressLike,
    depositorWallet: AddressLike,
    quantity: BigNumberish,
    newWalletOwedQuantity: BigNumberish,
    newVaultTotalOwedQuantity: BigNumberish,
  ];
  export type OutputTuple = [
    managerWallet: string,
    depositorWallet: string,
    quantity: bigint,
    newWalletOwedQuantity: bigint,
    newVaultTotalOwedQuantity: bigint,
  ];
  export interface OutputObject {
    managerWallet: string;
    depositorWallet: string;
    quantity: bigint;
    newWalletOwedQuantity: bigint;
    newVaultTotalOwedQuantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalFromManagedAccountCanceledEvent {
  export type InputTuple = [
    managerWallet: AddressLike,
    depositorWallet: AddressLike,
    quantity: BigNumberish,
  ];
  export type OutputTuple = [
    managerWallet: string,
    depositorWallet: string,
    quantity: bigint,
  ];
  export interface OutputObject {
    managerWallet: string;
    depositorWallet: string;
    quantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalFromManagedAccountReadyToApplyEvent {
  export type InputTuple = [
    withdrawal: WithdrawalFromManagedAccountStruct,
    totalShareSupply: BigNumberish,
    numberOfWithdrawalsInQueue: BigNumberish,
  ];
  export type OutputTuple = [
    withdrawal: WithdrawalFromManagedAccountStructOutput,
    totalShareSupply: bigint,
    numberOfWithdrawalsInQueue: bigint,
  ];
  export interface OutputObject {
    withdrawal: WithdrawalFromManagedAccountStructOutput;
    totalShareSupply: bigint;
    numberOfWithdrawalsInQueue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FixedIncomeVaultProvider_v1 extends BaseContract {
  connect(runner?: ContractRunner | null): FixedIncomeVaultProvider_v1;
  waitForDeployment(): Promise<this>;

  interface: FixedIncomeVaultProvider_v1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  INTEREST_PERIOD_IN_S: TypedContractMethod<[], [bigint], 'view'>;

  MAX_INTEREST_MULTIPLIER: TypedContractMethod<[], [bigint], 'view'>;

  MAX_MANAGED_ACCOUNT_UPGRADE_BLOCK_TIMESTAMP_DELAY_IN_S: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  MAX_MAXIMUM_NET_DEPOSITS: TypedContractMethod<[], [bigint], 'view'>;

  MAX_MAXIMUM_TOTAL_OWED_QUANTITY_AVAILABLE_MULTIPLIER_TO_INITIATE_EXIT: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  MAX_MINIMUM_TOTAL_OWED_QUANTITY_AVAILABLE_MULTIPLIER_TO_ALLOW_MANAGER_WALLET_WITHDRAWAL: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  MAX_MINIMUM_UNAPPLIED_DEPOSIT_OR_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  MAX_WITHDRAWAL_LIMIT_PERCENT_FOR_DEPOSITORS: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  MAX_WITHDRAWAL_LIMIT_PERCENT_FOR_VAULT: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  MAX_WITHDRAWAL_LIMIT_WINDOW_SIZE_IN_S: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  MINIMUM_WITHDRAWAL_MAXIMUM_GAS_FEE: TypedContractMethod<[], [bigint], 'view'>;

  MIN_INTEREST_MULTIPLIER: TypedContractMethod<[], [bigint], 'view'>;

  MIN_MANAGED_ACCOUNT_UPGRADE_BLOCK_TIMESTAMP_DELAY_IN_S: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  MIN_MAXIMUM_NET_DEPOSITS: TypedContractMethod<[], [bigint], 'view'>;

  MIN_MAXIMUM_TOTAL_OWED_QUANTITY_AVAILABLE_MULTIPLIER_TO_INITIATE_EXIT: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  MIN_MINIMUM_TOTAL_OWED_QUANTITY_AVAILABLE_MULTIPLIER_TO_ALLOW_MANAGER_WALLET_WITHDRAWAL: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  MIN_MINIMUM_UNAPPLIED_DEPOSIT_OR_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  MIN_WITHDRAWAL_LIMIT_PERCENT_FOR_DEPOSITORS: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  MIN_WITHDRAWAL_LIMIT_PERCENT_FOR_VAULT: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  MIN_WITHDRAWAL_LIMIT_WINDOW_SIZE_IN_S: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  addManagedAccount: TypedContractMethod<
    [managerWallet: AddressLike, payload: BytesLike],
    [void],
    'nonpayable'
  >;

  adminWallet: TypedContractMethod<[], [string], 'view'>;

  applyPendingDeposit: TypedContractMethod<
    [
      depositIndex: BigNumberish,
      managerWallet: AddressLike,
      quantity: BigNumberish,
    ],
    [void],
    'nonpayable'
  >;

  applyPendingWithdrawal: TypedContractMethod<
    [
      gasFee: BigNumberish,
      arg1: BigNumberish,
      managerWallet: AddressLike,
      withdrawalHash: BytesLike,
    ],
    [void],
    'nonpayable'
  >;

  cancelManagedAccountUpgrade: TypedContractMethod<[], [void], 'nonpayable'>;

  cancelPendingWithdrawal: TypedContractMethod<
    [
      gasFee: BigNumberish,
      managerWallet: AddressLike,
      withdrawalHash: BytesLike,
    ],
    [void],
    'nonpayable'
  >;

  custodian: TypedContractMethod<[], [string], 'view'>;

  deposit: TypedContractMethod<
    [
      depositIndex: BigNumberish,
      quantity: BigNumberish,
      sourceWallet: AddressLike,
      depositorWallet: AddressLike,
      managerWallet: AddressLike,
      managedAccountProviderPayload: BytesLike,
    ],
    [void],
    'nonpayable'
  >;

  emitEventsForFrontOfDepositAndWithdrawalQueues: TypedContractMethod<
    [managerWallet: AddressLike],
    [void],
    'nonpayable'
  >;

  exitWallet: TypedContractMethod<
    [managerWallet: AddressLike],
    [void],
    'nonpayable'
  >;

  finalizeManagedAccountUpgrade: TypedContractMethod<[], [void], 'nonpayable'>;

  initiateManagedAccountUpgrade: TypedContractMethod<
    [payload: BytesLike],
    [void],
    'nonpayable'
  >;

  intervalTick: TypedContractMethod<[arg0: BytesLike], [void], 'view'>;

  isAddManagedAccountEnabled: TypedContractMethod<[], [boolean], 'view'>;

  isApplyDepositEnabled: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    'view'
  >;

  isDepositEnabled: TypedContractMethod<
    [managerWallet: AddressLike],
    [boolean],
    'view'
  >;

  liquidateManagerWallet: TypedContractMethod<
    [managerWallet: AddressLike],
    [void],
    'nonpayable'
  >;

  loadVaultBalanceForWalletSummary: TypedContractMethod<
    [managerWallet: AddressLike, depositorWallet: AddressLike],
    [FixedIncomeVaultProvider_v1.VaultBalanceForWalletSummaryStructOutput],
    'view'
  >;

  loadVaultConfiguration: TypedContractMethod<
    [managerWallet: AddressLike, index: BigNumberish],
    [FixedIncomeVaultProvider_v1.VaultConfigurationFieldsStructOutput],
    'view'
  >;

  loadVaultConfigurationsLength: TypedContractMethod<
    [managerWallet: AddressLike],
    [bigint],
    'view'
  >;

  loadVaultDepositQueueItem: TypedContractMethod<
    [managerWallet: AddressLike, index: BigNumberish],
    [VaultDepositQueue.ItemStructOutput],
    'view'
  >;

  loadVaultDepositQueueLength: TypedContractMethod<
    [managerWallet: AddressLike],
    [bigint],
    'view'
  >;

  loadVaultSummary: TypedContractMethod<
    [managerWallet: AddressLike],
    [FixedIncomeVaultProvider_v1.VaultSummaryStructOutput],
    'view'
  >;

  loadVaultWithdrawQueueItem: TypedContractMethod<
    [managerWallet: AddressLike, index: BigNumberish],
    [WithdrawalFromManagedAccountStructOutput],
    'view'
  >;

  loadVaultWithdrawQueueLength: TypedContractMethod<
    [managerWallet: AddressLike],
    [bigint],
    'view'
  >;

  managedAccountUpgradeBlockTimestampDelayInS: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  ownerWallet: TypedContractMethod<[], [string], 'view'>;

  removeAdmin: TypedContractMethod<[], [void], 'nonpayable'>;

  removeOwner: TypedContractMethod<[], [void], 'nonpayable'>;

  seenDepositIndexes: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    'view'
  >;

  seenWithdrawalHashes: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    'view'
  >;

  setAddManagedAccountEnabledAdmin: TypedContractMethod<
    [isAddManagedAccountEnabled: boolean],
    [void],
    'nonpayable'
  >;

  setAdmin: TypedContractMethod<[newAdmin: AddressLike], [void], 'nonpayable'>;

  setDepositEnabled: TypedContractMethod<
    [isEnabled: boolean],
    [void],
    'nonpayable'
  >;

  setDepositEnabledAdmin: TypedContractMethod<
    [isDepositEnabled: boolean, isApplyDepositEnabled: boolean],
    [void],
    'nonpayable'
  >;

  setManagedAccountUpgradeBlockTimestampDelay: TypedContractMethod<
    [newManagedAccountUpgradeBlockTimestampDelayInS: BigNumberish],
    [void],
    'nonpayable'
  >;

  setOwner: TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;

  setWithdrawalDispatcher: TypedContractMethod<
    [newWithdrawalDispatcherWallet: AddressLike],
    [void],
    'nonpayable'
  >;

  skim: TypedContractMethod<[tokenAddress: AddressLike], [void], 'nonpayable'>;

  vaultConfigurationUpgradesByManagerWallet: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        boolean,
        FixedIncomeVaultProvider_v1.VaultConfigurationFieldsStructOutput,
        bigint,
      ] & {
        exists: boolean;
        newVaultConfigurationFields: FixedIncomeVaultProvider_v1.VaultConfigurationFieldsStructOutput;
        blockTimestampThreshold: bigint;
      },
    ],
    'view'
  >;

  withdrawByQuantity: TypedContractMethod<
    [withdrawal: WithdrawalFromManagedAccountByQuantityStruct],
    [void],
    'nonpayable'
  >;

  withdrawByShares: TypedContractMethod<
    [arg0: WithdrawalFromManagedAccountBySharesStruct],
    [void],
    'view'
  >;

  withdrawExit: TypedContractMethod<
    [managerWallet: AddressLike, depositorWallet: AddressLike],
    [void],
    'nonpayable'
  >;

  withdrawalDispatcherWallet: TypedContractMethod<[], [string], 'view'>;

  withdrawalLimitWindowSizeInS: TypedContractMethod<[], [bigint], 'view'>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: 'INTEREST_PERIOD_IN_S',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MAX_INTEREST_MULTIPLIER',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MAX_MANAGED_ACCOUNT_UPGRADE_BLOCK_TIMESTAMP_DELAY_IN_S',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MAX_MAXIMUM_NET_DEPOSITS',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MAX_MAXIMUM_TOTAL_OWED_QUANTITY_AVAILABLE_MULTIPLIER_TO_INITIATE_EXIT',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MAX_MINIMUM_TOTAL_OWED_QUANTITY_AVAILABLE_MULTIPLIER_TO_ALLOW_MANAGER_WALLET_WITHDRAWAL',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MAX_MINIMUM_UNAPPLIED_DEPOSIT_OR_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MAX_WITHDRAWAL_LIMIT_PERCENT_FOR_DEPOSITORS',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MAX_WITHDRAWAL_LIMIT_PERCENT_FOR_VAULT',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MAX_WITHDRAWAL_LIMIT_WINDOW_SIZE_IN_S',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MINIMUM_WITHDRAWAL_MAXIMUM_GAS_FEE',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MIN_INTEREST_MULTIPLIER',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MIN_MANAGED_ACCOUNT_UPGRADE_BLOCK_TIMESTAMP_DELAY_IN_S',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MIN_MAXIMUM_NET_DEPOSITS',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MIN_MAXIMUM_TOTAL_OWED_QUANTITY_AVAILABLE_MULTIPLIER_TO_INITIATE_EXIT',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MIN_MINIMUM_TOTAL_OWED_QUANTITY_AVAILABLE_MULTIPLIER_TO_ALLOW_MANAGER_WALLET_WITHDRAWAL',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MIN_MINIMUM_UNAPPLIED_DEPOSIT_OR_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MIN_WITHDRAWAL_LIMIT_PERCENT_FOR_DEPOSITORS',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MIN_WITHDRAWAL_LIMIT_PERCENT_FOR_VAULT',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MIN_WITHDRAWAL_LIMIT_WINDOW_SIZE_IN_S',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'addManagedAccount',
  ): TypedContractMethod<
    [managerWallet: AddressLike, payload: BytesLike],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'adminWallet',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'applyPendingDeposit',
  ): TypedContractMethod<
    [
      depositIndex: BigNumberish,
      managerWallet: AddressLike,
      quantity: BigNumberish,
    ],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'applyPendingWithdrawal',
  ): TypedContractMethod<
    [
      gasFee: BigNumberish,
      arg1: BigNumberish,
      managerWallet: AddressLike,
      withdrawalHash: BytesLike,
    ],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'cancelManagedAccountUpgrade',
  ): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'cancelPendingWithdrawal',
  ): TypedContractMethod<
    [
      gasFee: BigNumberish,
      managerWallet: AddressLike,
      withdrawalHash: BytesLike,
    ],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'custodian',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'deposit',
  ): TypedContractMethod<
    [
      depositIndex: BigNumberish,
      quantity: BigNumberish,
      sourceWallet: AddressLike,
      depositorWallet: AddressLike,
      managerWallet: AddressLike,
      managedAccountProviderPayload: BytesLike,
    ],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'emitEventsForFrontOfDepositAndWithdrawalQueues',
  ): TypedContractMethod<[managerWallet: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'exitWallet',
  ): TypedContractMethod<[managerWallet: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'finalizeManagedAccountUpgrade',
  ): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'initiateManagedAccountUpgrade',
  ): TypedContractMethod<[payload: BytesLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'intervalTick',
  ): TypedContractMethod<[arg0: BytesLike], [void], 'view'>;
  getFunction(
    nameOrSignature: 'isAddManagedAccountEnabled',
  ): TypedContractMethod<[], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'isApplyDepositEnabled',
  ): TypedContractMethod<[arg0: AddressLike], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'isDepositEnabled',
  ): TypedContractMethod<[managerWallet: AddressLike], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'liquidateManagerWallet',
  ): TypedContractMethod<[managerWallet: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'loadVaultBalanceForWalletSummary',
  ): TypedContractMethod<
    [managerWallet: AddressLike, depositorWallet: AddressLike],
    [FixedIncomeVaultProvider_v1.VaultBalanceForWalletSummaryStructOutput],
    'view'
  >;
  getFunction(
    nameOrSignature: 'loadVaultConfiguration',
  ): TypedContractMethod<
    [managerWallet: AddressLike, index: BigNumberish],
    [FixedIncomeVaultProvider_v1.VaultConfigurationFieldsStructOutput],
    'view'
  >;
  getFunction(
    nameOrSignature: 'loadVaultConfigurationsLength',
  ): TypedContractMethod<[managerWallet: AddressLike], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'loadVaultDepositQueueItem',
  ): TypedContractMethod<
    [managerWallet: AddressLike, index: BigNumberish],
    [VaultDepositQueue.ItemStructOutput],
    'view'
  >;
  getFunction(
    nameOrSignature: 'loadVaultDepositQueueLength',
  ): TypedContractMethod<[managerWallet: AddressLike], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'loadVaultSummary',
  ): TypedContractMethod<
    [managerWallet: AddressLike],
    [FixedIncomeVaultProvider_v1.VaultSummaryStructOutput],
    'view'
  >;
  getFunction(
    nameOrSignature: 'loadVaultWithdrawQueueItem',
  ): TypedContractMethod<
    [managerWallet: AddressLike, index: BigNumberish],
    [WithdrawalFromManagedAccountStructOutput],
    'view'
  >;
  getFunction(
    nameOrSignature: 'loadVaultWithdrawQueueLength',
  ): TypedContractMethod<[managerWallet: AddressLike], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'managedAccountUpgradeBlockTimestampDelayInS',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'ownerWallet',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'removeAdmin',
  ): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'removeOwner',
  ): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'seenDepositIndexes',
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'seenWithdrawalHashes',
  ): TypedContractMethod<[arg0: BytesLike], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'setAddManagedAccountEnabledAdmin',
  ): TypedContractMethod<
    [isAddManagedAccountEnabled: boolean],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'setAdmin',
  ): TypedContractMethod<[newAdmin: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setDepositEnabled',
  ): TypedContractMethod<[isEnabled: boolean], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setDepositEnabledAdmin',
  ): TypedContractMethod<
    [isDepositEnabled: boolean, isApplyDepositEnabled: boolean],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'setManagedAccountUpgradeBlockTimestampDelay',
  ): TypedContractMethod<
    [newManagedAccountUpgradeBlockTimestampDelayInS: BigNumberish],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'setOwner',
  ): TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setWithdrawalDispatcher',
  ): TypedContractMethod<
    [newWithdrawalDispatcherWallet: AddressLike],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'skim',
  ): TypedContractMethod<[tokenAddress: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'vaultConfigurationUpgradesByManagerWallet',
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        boolean,
        FixedIncomeVaultProvider_v1.VaultConfigurationFieldsStructOutput,
        bigint,
      ] & {
        exists: boolean;
        newVaultConfigurationFields: FixedIncomeVaultProvider_v1.VaultConfigurationFieldsStructOutput;
        blockTimestampThreshold: bigint;
      },
    ],
    'view'
  >;
  getFunction(
    nameOrSignature: 'withdrawByQuantity',
  ): TypedContractMethod<
    [withdrawal: WithdrawalFromManagedAccountByQuantityStruct],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'withdrawByShares',
  ): TypedContractMethod<
    [arg0: WithdrawalFromManagedAccountBySharesStruct],
    [void],
    'view'
  >;
  getFunction(
    nameOrSignature: 'withdrawExit',
  ): TypedContractMethod<
    [managerWallet: AddressLike, depositorWallet: AddressLike],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'withdrawalDispatcherWallet',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'withdrawalLimitWindowSizeInS',
  ): TypedContractMethod<[], [bigint], 'view'>;

  getEvent(
    key: 'AddManagedAccountsDisabledAdmin',
  ): TypedContractEvent<
    AddManagedAccountsDisabledAdminEvent.InputTuple,
    AddManagedAccountsDisabledAdminEvent.OutputTuple,
    AddManagedAccountsDisabledAdminEvent.OutputObject
  >;
  getEvent(
    key: 'AddManagedAccountsEnabledAdmin',
  ): TypedContractEvent<
    AddManagedAccountsEnabledAdminEvent.InputTuple,
    AddManagedAccountsEnabledAdminEvent.OutputTuple,
    AddManagedAccountsEnabledAdminEvent.OutputObject
  >;
  getEvent(
    key: 'DepositToManagedAccountApplied',
  ): TypedContractEvent<
    DepositToManagedAccountAppliedEvent.InputTuple,
    DepositToManagedAccountAppliedEvent.OutputTuple,
    DepositToManagedAccountAppliedEvent.OutputObject
  >;
  getEvent(
    key: 'DepositToManagedAccountReadyToApply',
  ): TypedContractEvent<
    DepositToManagedAccountReadyToApplyEvent.InputTuple,
    DepositToManagedAccountReadyToApplyEvent.OutputTuple,
    DepositToManagedAccountReadyToApplyEvent.OutputObject
  >;
  getEvent(
    key: 'DepositsDisabled',
  ): TypedContractEvent<
    DepositsDisabledEvent.InputTuple,
    DepositsDisabledEvent.OutputTuple,
    DepositsDisabledEvent.OutputObject
  >;
  getEvent(
    key: 'DepositsDisabledAdmin',
  ): TypedContractEvent<
    DepositsDisabledAdminEvent.InputTuple,
    DepositsDisabledAdminEvent.OutputTuple,
    DepositsDisabledAdminEvent.OutputObject
  >;
  getEvent(
    key: 'DepositsEnabled',
  ): TypedContractEvent<
    DepositsEnabledEvent.InputTuple,
    DepositsEnabledEvent.OutputTuple,
    DepositsEnabledEvent.OutputObject
  >;
  getEvent(
    key: 'DepositsEnabledAdmin',
  ): TypedContractEvent<
    DepositsEnabledAdminEvent.InputTuple,
    DepositsEnabledAdminEvent.OutputTuple,
    DepositsEnabledAdminEvent.OutputObject
  >;
  getEvent(
    key: 'LiquidatedVaultPendingDepositRefundFailed',
  ): TypedContractEvent<
    LiquidatedVaultPendingDepositRefundFailedEvent.InputTuple,
    LiquidatedVaultPendingDepositRefundFailedEvent.OutputTuple,
    LiquidatedVaultPendingDepositRefundFailedEvent.OutputObject
  >;
  getEvent(
    key: 'ManagedAccountAdded',
  ): TypedContractEvent<
    ManagedAccountAddedEvent.InputTuple,
    ManagedAccountAddedEvent.OutputTuple,
    ManagedAccountAddedEvent.OutputObject
  >;
  getEvent(
    key: 'ManagedAccountUpgradeBlockTimestampDelayChanged',
  ): TypedContractEvent<
    ManagedAccountUpgradeBlockTimestampDelayChangedEvent.InputTuple,
    ManagedAccountUpgradeBlockTimestampDelayChangedEvent.OutputTuple,
    ManagedAccountUpgradeBlockTimestampDelayChangedEvent.OutputObject
  >;
  getEvent(
    key: 'ManagedAccountUpgradeCanceled',
  ): TypedContractEvent<
    ManagedAccountUpgradeCanceledEvent.InputTuple,
    ManagedAccountUpgradeCanceledEvent.OutputTuple,
    ManagedAccountUpgradeCanceledEvent.OutputObject
  >;
  getEvent(
    key: 'ManagedAccountUpgradeFinalized',
  ): TypedContractEvent<
    ManagedAccountUpgradeFinalizedEvent.InputTuple,
    ManagedAccountUpgradeFinalizedEvent.OutputTuple,
    ManagedAccountUpgradeFinalizedEvent.OutputObject
  >;
  getEvent(
    key: 'ManagedAccountUpgradeInitiated',
  ): TypedContractEvent<
    ManagedAccountUpgradeInitiatedEvent.InputTuple,
    ManagedAccountUpgradeInitiatedEvent.OutputTuple,
    ManagedAccountUpgradeInitiatedEvent.OutputObject
  >;
  getEvent(
    key: 'ManagerWalletLiquidated',
  ): TypedContractEvent<
    ManagerWalletLiquidatedEvent.InputTuple,
    ManagerWalletLiquidatedEvent.OutputTuple,
    ManagerWalletLiquidatedEvent.OutputObject
  >;
  getEvent(
    key: 'WithdrawalDispatcherChanged',
  ): TypedContractEvent<
    WithdrawalDispatcherChangedEvent.InputTuple,
    WithdrawalDispatcherChangedEvent.OutputTuple,
    WithdrawalDispatcherChangedEvent.OutputObject
  >;
  getEvent(
    key: 'WithdrawalFromManagedAccountApplied',
  ): TypedContractEvent<
    WithdrawalFromManagedAccountAppliedEvent.InputTuple,
    WithdrawalFromManagedAccountAppliedEvent.OutputTuple,
    WithdrawalFromManagedAccountAppliedEvent.OutputObject
  >;
  getEvent(
    key: 'WithdrawalFromManagedAccountCanceled',
  ): TypedContractEvent<
    WithdrawalFromManagedAccountCanceledEvent.InputTuple,
    WithdrawalFromManagedAccountCanceledEvent.OutputTuple,
    WithdrawalFromManagedAccountCanceledEvent.OutputObject
  >;
  getEvent(
    key: 'WithdrawalFromManagedAccountReadyToApply',
  ): TypedContractEvent<
    WithdrawalFromManagedAccountReadyToApplyEvent.InputTuple,
    WithdrawalFromManagedAccountReadyToApplyEvent.OutputTuple,
    WithdrawalFromManagedAccountReadyToApplyEvent.OutputObject
  >;

  filters: {
    'AddManagedAccountsDisabledAdmin()': TypedContractEvent<
      AddManagedAccountsDisabledAdminEvent.InputTuple,
      AddManagedAccountsDisabledAdminEvent.OutputTuple,
      AddManagedAccountsDisabledAdminEvent.OutputObject
    >;
    AddManagedAccountsDisabledAdmin: TypedContractEvent<
      AddManagedAccountsDisabledAdminEvent.InputTuple,
      AddManagedAccountsDisabledAdminEvent.OutputTuple,
      AddManagedAccountsDisabledAdminEvent.OutputObject
    >;

    'AddManagedAccountsEnabledAdmin()': TypedContractEvent<
      AddManagedAccountsEnabledAdminEvent.InputTuple,
      AddManagedAccountsEnabledAdminEvent.OutputTuple,
      AddManagedAccountsEnabledAdminEvent.OutputObject
    >;
    AddManagedAccountsEnabledAdmin: TypedContractEvent<
      AddManagedAccountsEnabledAdminEvent.InputTuple,
      AddManagedAccountsEnabledAdminEvent.OutputTuple,
      AddManagedAccountsEnabledAdminEvent.OutputObject
    >;

    'DepositToManagedAccountApplied(address,address,uint64,uint64,uint64)': TypedContractEvent<
      DepositToManagedAccountAppliedEvent.InputTuple,
      DepositToManagedAccountAppliedEvent.OutputTuple,
      DepositToManagedAccountAppliedEvent.OutputObject
    >;
    DepositToManagedAccountApplied: TypedContractEvent<
      DepositToManagedAccountAppliedEvent.InputTuple,
      DepositToManagedAccountAppliedEvent.OutputTuple,
      DepositToManagedAccountAppliedEvent.OutputObject
    >;

    'DepositToManagedAccountReadyToApply(uint64,uint64,address,address,address)': TypedContractEvent<
      DepositToManagedAccountReadyToApplyEvent.InputTuple,
      DepositToManagedAccountReadyToApplyEvent.OutputTuple,
      DepositToManagedAccountReadyToApplyEvent.OutputObject
    >;
    DepositToManagedAccountReadyToApply: TypedContractEvent<
      DepositToManagedAccountReadyToApplyEvent.InputTuple,
      DepositToManagedAccountReadyToApplyEvent.OutputTuple,
      DepositToManagedAccountReadyToApplyEvent.OutputObject
    >;

    'DepositsDisabled(address)': TypedContractEvent<
      DepositsDisabledEvent.InputTuple,
      DepositsDisabledEvent.OutputTuple,
      DepositsDisabledEvent.OutputObject
    >;
    DepositsDisabled: TypedContractEvent<
      DepositsDisabledEvent.InputTuple,
      DepositsDisabledEvent.OutputTuple,
      DepositsDisabledEvent.OutputObject
    >;

    'DepositsDisabledAdmin(bool,bool)': TypedContractEvent<
      DepositsDisabledAdminEvent.InputTuple,
      DepositsDisabledAdminEvent.OutputTuple,
      DepositsDisabledAdminEvent.OutputObject
    >;
    DepositsDisabledAdmin: TypedContractEvent<
      DepositsDisabledAdminEvent.InputTuple,
      DepositsDisabledAdminEvent.OutputTuple,
      DepositsDisabledAdminEvent.OutputObject
    >;

    'DepositsEnabled(address)': TypedContractEvent<
      DepositsEnabledEvent.InputTuple,
      DepositsEnabledEvent.OutputTuple,
      DepositsEnabledEvent.OutputObject
    >;
    DepositsEnabled: TypedContractEvent<
      DepositsEnabledEvent.InputTuple,
      DepositsEnabledEvent.OutputTuple,
      DepositsEnabledEvent.OutputObject
    >;

    'DepositsEnabledAdmin()': TypedContractEvent<
      DepositsEnabledAdminEvent.InputTuple,
      DepositsEnabledAdminEvent.OutputTuple,
      DepositsEnabledAdminEvent.OutputObject
    >;
    DepositsEnabledAdmin: TypedContractEvent<
      DepositsEnabledAdminEvent.InputTuple,
      DepositsEnabledAdminEvent.OutputTuple,
      DepositsEnabledAdminEvent.OutputObject
    >;

    'LiquidatedVaultPendingDepositRefundFailed(address,uint256,bytes)': TypedContractEvent<
      LiquidatedVaultPendingDepositRefundFailedEvent.InputTuple,
      LiquidatedVaultPendingDepositRefundFailedEvent.OutputTuple,
      LiquidatedVaultPendingDepositRefundFailedEvent.OutputObject
    >;
    LiquidatedVaultPendingDepositRefundFailed: TypedContractEvent<
      LiquidatedVaultPendingDepositRefundFailedEvent.InputTuple,
      LiquidatedVaultPendingDepositRefundFailedEvent.OutputTuple,
      LiquidatedVaultPendingDepositRefundFailedEvent.OutputObject
    >;

    'ManagedAccountAdded(address)': TypedContractEvent<
      ManagedAccountAddedEvent.InputTuple,
      ManagedAccountAddedEvent.OutputTuple,
      ManagedAccountAddedEvent.OutputObject
    >;
    ManagedAccountAdded: TypedContractEvent<
      ManagedAccountAddedEvent.InputTuple,
      ManagedAccountAddedEvent.OutputTuple,
      ManagedAccountAddedEvent.OutputObject
    >;

    'ManagedAccountUpgradeBlockTimestampDelayChanged(uint256,uint256)': TypedContractEvent<
      ManagedAccountUpgradeBlockTimestampDelayChangedEvent.InputTuple,
      ManagedAccountUpgradeBlockTimestampDelayChangedEvent.OutputTuple,
      ManagedAccountUpgradeBlockTimestampDelayChangedEvent.OutputObject
    >;
    ManagedAccountUpgradeBlockTimestampDelayChanged: TypedContractEvent<
      ManagedAccountUpgradeBlockTimestampDelayChangedEvent.InputTuple,
      ManagedAccountUpgradeBlockTimestampDelayChangedEvent.OutputTuple,
      ManagedAccountUpgradeBlockTimestampDelayChangedEvent.OutputObject
    >;

    'ManagedAccountUpgradeCanceled(address)': TypedContractEvent<
      ManagedAccountUpgradeCanceledEvent.InputTuple,
      ManagedAccountUpgradeCanceledEvent.OutputTuple,
      ManagedAccountUpgradeCanceledEvent.OutputObject
    >;
    ManagedAccountUpgradeCanceled: TypedContractEvent<
      ManagedAccountUpgradeCanceledEvent.InputTuple,
      ManagedAccountUpgradeCanceledEvent.OutputTuple,
      ManagedAccountUpgradeCanceledEvent.OutputObject
    >;

    'ManagedAccountUpgradeFinalized(address)': TypedContractEvent<
      ManagedAccountUpgradeFinalizedEvent.InputTuple,
      ManagedAccountUpgradeFinalizedEvent.OutputTuple,
      ManagedAccountUpgradeFinalizedEvent.OutputObject
    >;
    ManagedAccountUpgradeFinalized: TypedContractEvent<
      ManagedAccountUpgradeFinalizedEvent.InputTuple,
      ManagedAccountUpgradeFinalizedEvent.OutputTuple,
      ManagedAccountUpgradeFinalizedEvent.OutputObject
    >;

    'ManagedAccountUpgradeInitiated(address,uint256)': TypedContractEvent<
      ManagedAccountUpgradeInitiatedEvent.InputTuple,
      ManagedAccountUpgradeInitiatedEvent.OutputTuple,
      ManagedAccountUpgradeInitiatedEvent.OutputObject
    >;
    ManagedAccountUpgradeInitiated: TypedContractEvent<
      ManagedAccountUpgradeInitiatedEvent.InputTuple,
      ManagedAccountUpgradeInitiatedEvent.OutputTuple,
      ManagedAccountUpgradeInitiatedEvent.OutputObject
    >;

    'ManagerWalletLiquidated(address)': TypedContractEvent<
      ManagerWalletLiquidatedEvent.InputTuple,
      ManagerWalletLiquidatedEvent.OutputTuple,
      ManagerWalletLiquidatedEvent.OutputObject
    >;
    ManagerWalletLiquidated: TypedContractEvent<
      ManagerWalletLiquidatedEvent.InputTuple,
      ManagerWalletLiquidatedEvent.OutputTuple,
      ManagerWalletLiquidatedEvent.OutputObject
    >;

    'WithdrawalDispatcherChanged(address,address)': TypedContractEvent<
      WithdrawalDispatcherChangedEvent.InputTuple,
      WithdrawalDispatcherChangedEvent.OutputTuple,
      WithdrawalDispatcherChangedEvent.OutputObject
    >;
    WithdrawalDispatcherChanged: TypedContractEvent<
      WithdrawalDispatcherChangedEvent.InputTuple,
      WithdrawalDispatcherChangedEvent.OutputTuple,
      WithdrawalDispatcherChangedEvent.OutputObject
    >;

    'WithdrawalFromManagedAccountApplied(address,address,uint64,uint64,uint64)': TypedContractEvent<
      WithdrawalFromManagedAccountAppliedEvent.InputTuple,
      WithdrawalFromManagedAccountAppliedEvent.OutputTuple,
      WithdrawalFromManagedAccountAppliedEvent.OutputObject
    >;
    WithdrawalFromManagedAccountApplied: TypedContractEvent<
      WithdrawalFromManagedAccountAppliedEvent.InputTuple,
      WithdrawalFromManagedAccountAppliedEvent.OutputTuple,
      WithdrawalFromManagedAccountAppliedEvent.OutputObject
    >;

    'WithdrawalFromManagedAccountCanceled(address,address,uint64)': TypedContractEvent<
      WithdrawalFromManagedAccountCanceledEvent.InputTuple,
      WithdrawalFromManagedAccountCanceledEvent.OutputTuple,
      WithdrawalFromManagedAccountCanceledEvent.OutputObject
    >;
    WithdrawalFromManagedAccountCanceled: TypedContractEvent<
      WithdrawalFromManagedAccountCanceledEvent.InputTuple,
      WithdrawalFromManagedAccountCanceledEvent.OutputTuple,
      WithdrawalFromManagedAccountCanceledEvent.OutputObject
    >;

    'WithdrawalFromManagedAccountReadyToApply(tuple,uint64,uint256)': TypedContractEvent<
      WithdrawalFromManagedAccountReadyToApplyEvent.InputTuple,
      WithdrawalFromManagedAccountReadyToApplyEvent.OutputTuple,
      WithdrawalFromManagedAccountReadyToApplyEvent.OutputObject
    >;
    WithdrawalFromManagedAccountReadyToApply: TypedContractEvent<
      WithdrawalFromManagedAccountReadyToApplyEvent.InputTuple,
      WithdrawalFromManagedAccountReadyToApplyEvent.OutputTuple,
      WithdrawalFromManagedAccountReadyToApplyEvent.OutputObject
    >;
  };
}
