/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from './common';

export type SendParamStruct = {
  dstEid: BigNumberish;
  to: BytesLike;
  amountLD: BigNumberish;
  minAmountLD: BigNumberish;
  extraOptions: BytesLike;
  composeMsg: BytesLike;
  oftCmd: BytesLike;
};

export type SendParamStructOutput = [
  dstEid: bigint,
  to: string,
  amountLD: bigint,
  minAmountLD: bigint,
  extraOptions: string,
  composeMsg: string,
  oftCmd: string,
] & {
  dstEid: bigint;
  to: string;
  amountLD: bigint;
  minAmountLD: bigint;
  extraOptions: string;
  composeMsg: string;
  oftCmd: string;
};

export type MessagingFeeStruct = {
  nativeFee: BigNumberish;
  lzTokenFee: BigNumberish;
};

export type MessagingFeeStructOutput = [
  nativeFee: bigint,
  lzTokenFee: bigint,
] & { nativeFee: bigint; lzTokenFee: bigint };

export interface IVaultComposerSyncInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'ASSET_ERC20'
      | 'ASSET_OFT'
      | 'ENDPOINT'
      | 'SHARE_ERC20'
      | 'SHARE_OFT'
      | 'VAULT'
      | 'VAULT_EID'
      | 'depositAndSend'
      | 'lzCompose'
      | 'quoteSend'
      | 'redeemAndSend',
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: 'Deposited' | 'Redeemed' | 'Refunded' | 'Sent',
  ): EventFragment;

  encodeFunctionData(
    functionFragment: 'ASSET_ERC20',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'ASSET_OFT', values?: undefined): string;
  encodeFunctionData(functionFragment: 'ENDPOINT', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'SHARE_ERC20',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'SHARE_OFT', values?: undefined): string;
  encodeFunctionData(functionFragment: 'VAULT', values?: undefined): string;
  encodeFunctionData(functionFragment: 'VAULT_EID', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'depositAndSend',
    values: [BigNumberish, SendParamStruct, AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'lzCompose',
    values: [AddressLike, BytesLike, BytesLike, AddressLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'quoteSend',
    values: [AddressLike, AddressLike, BigNumberish, SendParamStruct],
  ): string;
  encodeFunctionData(
    functionFragment: 'redeemAndSend',
    values: [BigNumberish, SendParamStruct, AddressLike],
  ): string;

  decodeFunctionResult(
    functionFragment: 'ASSET_ERC20',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'ASSET_OFT', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'ENDPOINT', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'SHARE_ERC20',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'SHARE_OFT', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'VAULT', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'VAULT_EID', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'depositAndSend',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'lzCompose', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'quoteSend', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'redeemAndSend',
    data: BytesLike,
  ): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [
    sender: BytesLike,
    recipient: BytesLike,
    dstEid: BigNumberish,
    assetAmt: BigNumberish,
    shareAmt: BigNumberish,
  ];
  export type OutputTuple = [
    sender: string,
    recipient: string,
    dstEid: bigint,
    assetAmt: bigint,
    shareAmt: bigint,
  ];
  export interface OutputObject {
    sender: string;
    recipient: string;
    dstEid: bigint;
    assetAmt: bigint;
    shareAmt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemedEvent {
  export type InputTuple = [
    sender: BytesLike,
    recipient: BytesLike,
    dstEid: BigNumberish,
    shareAmt: BigNumberish,
    assetAmt: BigNumberish,
  ];
  export type OutputTuple = [
    sender: string,
    recipient: string,
    dstEid: bigint,
    shareAmt: bigint,
    assetAmt: bigint,
  ];
  export interface OutputObject {
    sender: string;
    recipient: string;
    dstEid: bigint;
    shareAmt: bigint;
    assetAmt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundedEvent {
  export type InputTuple = [guid: BytesLike];
  export type OutputTuple = [guid: string];
  export interface OutputObject {
    guid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SentEvent {
  export type InputTuple = [guid: BytesLike];
  export type OutputTuple = [guid: string];
  export interface OutputObject {
    guid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IVaultComposerSync extends BaseContract {
  connect(runner?: ContractRunner | null): IVaultComposerSync;
  waitForDeployment(): Promise<this>;

  interface: IVaultComposerSyncInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  ASSET_ERC20: TypedContractMethod<[], [string], 'view'>;

  ASSET_OFT: TypedContractMethod<[], [string], 'view'>;

  ENDPOINT: TypedContractMethod<[], [string], 'view'>;

  SHARE_ERC20: TypedContractMethod<[], [string], 'view'>;

  SHARE_OFT: TypedContractMethod<[], [string], 'view'>;

  VAULT: TypedContractMethod<[], [string], 'view'>;

  VAULT_EID: TypedContractMethod<[], [bigint], 'view'>;

  depositAndSend: TypedContractMethod<
    [
      assetAmount: BigNumberish,
      sendParam: SendParamStruct,
      refundAddress: AddressLike,
    ],
    [void],
    'payable'
  >;

  lzCompose: TypedContractMethod<
    [
      _from: AddressLike,
      _guid: BytesLike,
      _message: BytesLike,
      _executor: AddressLike,
      _extraData: BytesLike,
    ],
    [void],
    'payable'
  >;

  quoteSend: TypedContractMethod<
    [
      from: AddressLike,
      targetOft: AddressLike,
      vaultInAmount: BigNumberish,
      sendParam: SendParamStruct,
    ],
    [MessagingFeeStructOutput],
    'view'
  >;

  redeemAndSend: TypedContractMethod<
    [
      shareAmount: BigNumberish,
      sendParam: SendParamStruct,
      refundAddress: AddressLike,
    ],
    [void],
    'payable'
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: 'ASSET_ERC20',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'ASSET_OFT',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'ENDPOINT',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'SHARE_ERC20',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'SHARE_OFT',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'VAULT',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'VAULT_EID',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'depositAndSend',
  ): TypedContractMethod<
    [
      assetAmount: BigNumberish,
      sendParam: SendParamStruct,
      refundAddress: AddressLike,
    ],
    [void],
    'payable'
  >;
  getFunction(
    nameOrSignature: 'lzCompose',
  ): TypedContractMethod<
    [
      _from: AddressLike,
      _guid: BytesLike,
      _message: BytesLike,
      _executor: AddressLike,
      _extraData: BytesLike,
    ],
    [void],
    'payable'
  >;
  getFunction(
    nameOrSignature: 'quoteSend',
  ): TypedContractMethod<
    [
      from: AddressLike,
      targetOft: AddressLike,
      vaultInAmount: BigNumberish,
      sendParam: SendParamStruct,
    ],
    [MessagingFeeStructOutput],
    'view'
  >;
  getFunction(
    nameOrSignature: 'redeemAndSend',
  ): TypedContractMethod<
    [
      shareAmount: BigNumberish,
      sendParam: SendParamStruct,
      refundAddress: AddressLike,
    ],
    [void],
    'payable'
  >;

  getEvent(
    key: 'Deposited',
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: 'Redeemed',
  ): TypedContractEvent<
    RedeemedEvent.InputTuple,
    RedeemedEvent.OutputTuple,
    RedeemedEvent.OutputObject
  >;
  getEvent(
    key: 'Refunded',
  ): TypedContractEvent<
    RefundedEvent.InputTuple,
    RefundedEvent.OutputTuple,
    RefundedEvent.OutputObject
  >;
  getEvent(
    key: 'Sent',
  ): TypedContractEvent<
    SentEvent.InputTuple,
    SentEvent.OutputTuple,
    SentEvent.OutputObject
  >;

  filters: {
    'Deposited(bytes32,bytes32,uint32,uint256,uint256)': TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    'Redeemed(bytes32,bytes32,uint32,uint256,uint256)': TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;
    Redeemed: TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;

    'Refunded(bytes32)': TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;
    Refunded: TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;

    'Sent(bytes32)': TypedContractEvent<
      SentEvent.InputTuple,
      SentEvent.OutputTuple,
      SentEvent.OutputObject
    >;
    Sent: TypedContractEvent<
      SentEvent.InputTuple,
      SentEvent.OutputTuple,
      SentEvent.OutputObject
    >;
  };
}
