/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from './common';

export type WithdrawalFromManagedAccountByQuantityStruct = {
  nonce: BigNumberish;
  managerWallet: AddressLike;
  depositorWallet: AddressLike;
  grossQuantity: BigNumberish;
  maxShares: BigNumberish;
  maximumGasFee: BigNumberish;
  managedAccountProvider: AddressLike;
  managedAccountProviderPayload: BytesLike;
  bridgeAdapter: AddressLike;
  bridgeAdapterPayload: BytesLike;
  gasFee: BigNumberish;
  walletSignature: BytesLike;
};

export type WithdrawalFromManagedAccountByQuantityStructOutput = [
  nonce: bigint,
  managerWallet: string,
  depositorWallet: string,
  grossQuantity: bigint,
  maxShares: bigint,
  maximumGasFee: bigint,
  managedAccountProvider: string,
  managedAccountProviderPayload: string,
  bridgeAdapter: string,
  bridgeAdapterPayload: string,
  gasFee: bigint,
  walletSignature: string,
] & {
  nonce: bigint;
  managerWallet: string;
  depositorWallet: string;
  grossQuantity: bigint;
  maxShares: bigint;
  maximumGasFee: bigint;
  managedAccountProvider: string;
  managedAccountProviderPayload: string;
  bridgeAdapter: string;
  bridgeAdapterPayload: string;
  gasFee: bigint;
  walletSignature: string;
};

export type WithdrawalFromManagedAccountBySharesStruct = {
  nonce: BigNumberish;
  managerWallet: AddressLike;
  depositorWallet: AddressLike;
  shares: BigNumberish;
  minimumQuantity: BigNumberish;
  maximumGasFee: BigNumberish;
  managedAccountProvider: AddressLike;
  managedAccountProviderPayload: BytesLike;
  bridgeAdapter: AddressLike;
  bridgeAdapterPayload: BytesLike;
  gasFee: BigNumberish;
  grossQuantity: BigNumberish;
  walletSignature: BytesLike;
};

export type WithdrawalFromManagedAccountBySharesStructOutput = [
  nonce: bigint,
  managerWallet: string,
  depositorWallet: string,
  shares: bigint,
  minimumQuantity: bigint,
  maximumGasFee: bigint,
  managedAccountProvider: string,
  managedAccountProviderPayload: string,
  bridgeAdapter: string,
  bridgeAdapterPayload: string,
  gasFee: bigint,
  grossQuantity: bigint,
  walletSignature: string,
] & {
  nonce: bigint;
  managerWallet: string;
  depositorWallet: string;
  shares: bigint;
  minimumQuantity: bigint;
  maximumGasFee: bigint;
  managedAccountProvider: string;
  managedAccountProviderPayload: string;
  bridgeAdapter: string;
  bridgeAdapterPayload: string;
  gasFee: bigint;
  grossQuantity: bigint;
  walletSignature: string;
};

export type WithdrawalFromManagedAccountStruct = {
  withdrawalType: BigNumberish;
  withdrawalByQuantity: WithdrawalFromManagedAccountByQuantityStruct;
  withdrawalByShares: WithdrawalFromManagedAccountBySharesStruct;
};

export type WithdrawalFromManagedAccountStructOutput = [
  withdrawalType: bigint,
  withdrawalByQuantity: WithdrawalFromManagedAccountByQuantityStructOutput,
  withdrawalByShares: WithdrawalFromManagedAccountBySharesStructOutput,
] & {
  withdrawalType: bigint;
  withdrawalByQuantity: WithdrawalFromManagedAccountByQuantityStructOutput;
  withdrawalByShares: WithdrawalFromManagedAccountBySharesStructOutput;
};

export declare namespace ProfitShareVaultProvider_v1 {
  export type VaultBalanceForWalletStruct = {
    costBasis: BigNumberish;
    sharesLockedForWithdrawal: BigNumberish;
    totalShares: BigNumberish;
  };

  export type VaultBalanceForWalletStructOutput = [
    costBasis: bigint,
    sharesLockedForWithdrawal: bigint,
    totalShares: bigint,
  ] & {
    costBasis: bigint;
    sharesLockedForWithdrawal: bigint;
    totalShares: bigint;
  };

  export type VaultConfigurationFieldsStruct = {
    managerWallet: AddressLike;
    carryFeeMultiplier: BigNumberish;
    depositFeeMultiplier: BigNumberish;
    managementFeeMultiplier: BigNumberish;
    managementFeePeriodInS: BigNumberish;
    maximumNetDeposits: BigNumberish;
    minimumUnappliedWithdrawalAgeInSToInitiateExit: BigNumberish;
  };

  export type VaultConfigurationFieldsStructOutput = [
    managerWallet: string,
    carryFeeMultiplier: bigint,
    depositFeeMultiplier: bigint,
    managementFeeMultiplier: bigint,
    managementFeePeriodInS: bigint,
    maximumNetDeposits: bigint,
    minimumUnappliedWithdrawalAgeInSToInitiateExit: bigint,
  ] & {
    managerWallet: string;
    carryFeeMultiplier: bigint;
    depositFeeMultiplier: bigint;
    managementFeeMultiplier: bigint;
    managementFeePeriodInS: bigint;
    maximumNetDeposits: bigint;
    minimumUnappliedWithdrawalAgeInSToInitiateExit: bigint;
  };

  export type VaultSummaryStruct = {
    isDepositEnabled: boolean;
    isExited: boolean;
    isLiquidated: boolean;
    configurationFields: ProfitShareVaultProvider_v1.VaultConfigurationFieldsStruct;
    netDeposits: BigNumberish;
    numDepositorWallets: BigNumberish;
    sharePrice: BigNumberish;
    totalShares: BigNumberish;
  };

  export type VaultSummaryStructOutput = [
    isDepositEnabled: boolean,
    isExited: boolean,
    isLiquidated: boolean,
    configurationFields: ProfitShareVaultProvider_v1.VaultConfigurationFieldsStructOutput,
    netDeposits: bigint,
    numDepositorWallets: bigint,
    sharePrice: bigint,
    totalShares: bigint,
  ] & {
    isDepositEnabled: boolean;
    isExited: boolean;
    isLiquidated: boolean;
    configurationFields: ProfitShareVaultProvider_v1.VaultConfigurationFieldsStructOutput;
    netDeposits: bigint;
    numDepositorWallets: bigint;
    sharePrice: bigint;
    totalShares: bigint;
  };
}

export declare namespace VaultDepositQueue {
  export type ItemStruct = {
    index: BigNumberish;
    quantity: BigNumberish;
    sourceWallet: AddressLike;
    depositorWallet: AddressLike;
    managerWallet: AddressLike;
    managedAccount: AddressLike;
    payload: BytesLike;
  };

  export type ItemStructOutput = [
    index: bigint,
    quantity: bigint,
    sourceWallet: string,
    depositorWallet: string,
    managerWallet: string,
    managedAccount: string,
    payload: string,
  ] & {
    index: bigint;
    quantity: bigint;
    sourceWallet: string;
    depositorWallet: string;
    managerWallet: string;
    managedAccount: string;
    payload: string;
  };
}

export interface ProfitShareVaultProvider_v1Interface extends Interface {
  getFunction(
    nameOrSignature:
      | 'INITIAL_SHARE_PRICE'
      | 'MAX_CARRY_FEE_MULTIPLIER'
      | 'MAX_DEPOSIT_FEE_MULTIPLIER'
      | 'MAX_MANAGEMENT_FEE_MULTIPLIER'
      | 'MAX_MANAGEMENT_FEE_PERIOD_IN_S'
      | 'MAX_MAXIMUM_NET_DEPOSITS'
      | 'MAX_MINIMUM_UNAPPLIED_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT'
      | 'MAX_MINIMUM_WITHDRAWAL_QUANTITY'
      | 'MIN_MANAGEMENT_FEE_PERIOD_IN_S'
      | 'MIN_MAXIMUM_NET_DEPOSITS'
      | 'MIN_MINIMUM_UNAPPLIED_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT'
      | 'MIN_MINIMUM_WITHDRAWAL_QUANTITY'
      | 'WORD_SIZE_IN_BYTES'
      | 'addManagedAccount'
      | 'adminWallet'
      | 'applyPendingDeposit'
      | 'applyPendingWithdrawal'
      | 'cancelManagedAccountUpgrade'
      | 'cancelPendingWithdrawal'
      | 'deposit'
      | 'emitEventsForFrontOfDepositAndWithdrawalQueues'
      | 'exchange'
      | 'exitWallet'
      | 'finalizeManagedAccountUpgrade'
      | 'initiateManagedAccountUpgrade'
      | 'intervalTick'
      | 'isAddManagedAccountEnabled'
      | 'isApplyDepositEnabled'
      | 'isDepositEnabled'
      | 'liquidateManagerWallet'
      | 'loadSharePrice'
      | 'loadVaultBalanceForWallet'
      | 'loadVaultDepositQueueItem'
      | 'loadVaultDepositQueueLength'
      | 'loadVaultSummary'
      | 'loadVaultWithdrawQueueItem'
      | 'loadVaultWithdrawQueueLength'
      | 'managedAccountUpgradeBlockTimestampDelayInS'
      | 'minimumWithdrawalQuantity'
      | 'ownerWallet'
      | 'removeAdmin'
      | 'removeOwner'
      | 'seenDepositIndexes'
      | 'seenWithdrawalHashes'
      | 'setAddManagedAccountEnabledAdmin'
      | 'setAdmin'
      | 'setDepositEnabled'
      | 'setDepositEnabledAdmin'
      | 'setManagedAccountUpgradeBlockTimestampDelay'
      | 'setMinimumWithdrawalQuantity'
      | 'setOwner'
      | 'setWithdrawalDispatcher'
      | 'skim'
      | 'vaultConfigurationUpgradesByManagerWallet'
      | 'withdrawByQuantity'
      | 'withdrawByShares'
      | 'withdrawExit'
      | 'withdrawalDispatcherWallet',
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | 'AddManagedAccountsDisabledAdmin'
      | 'AddManagedAccountsEnabledAdmin'
      | 'DepositToManagedAccountReadyToApply'
      | 'DepositsDisabled'
      | 'DepositsDisabledAdmin'
      | 'DepositsEnabled'
      | 'DepositsEnabledAdmin'
      | 'LiquidatedVaultPendingDepositRefundFailed'
      | 'ManagedAccountAdded'
      | 'ManagedAccountUpgradeBlockTimestampDelayChanged'
      | 'ManagedAccountUpgradeCanceled'
      | 'ManagedAccountUpgradeFinalized'
      | 'ManagedAccountUpgradeInitiated'
      | 'MinimumWithdrawalQuantityChanged'
      | 'VaultLiquidated'
      | 'VaultSharesBurned'
      | 'VaultSharesMinted'
      | 'WithdrawalDispatcherChanged'
      | 'WithdrawalFromManagedAccountCanceled'
      | 'WithdrawalFromManagedAccountReadyToApply',
  ): EventFragment;

  encodeFunctionData(
    functionFragment: 'INITIAL_SHARE_PRICE',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MAX_CARRY_FEE_MULTIPLIER',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MAX_DEPOSIT_FEE_MULTIPLIER',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MAX_MANAGEMENT_FEE_MULTIPLIER',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MAX_MANAGEMENT_FEE_PERIOD_IN_S',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MAX_MAXIMUM_NET_DEPOSITS',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MAX_MINIMUM_UNAPPLIED_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MAX_MINIMUM_WITHDRAWAL_QUANTITY',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MIN_MANAGEMENT_FEE_PERIOD_IN_S',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MIN_MAXIMUM_NET_DEPOSITS',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MIN_MINIMUM_UNAPPLIED_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'MIN_MINIMUM_WITHDRAWAL_QUANTITY',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'WORD_SIZE_IN_BYTES',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'addManagedAccount',
    values: [AddressLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'adminWallet',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'applyPendingDeposit',
    values: [BigNumberish, AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'applyPendingWithdrawal',
    values: [BigNumberish, BigNumberish, AddressLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'cancelManagedAccountUpgrade',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'cancelPendingWithdrawal',
    values: [BigNumberish, AddressLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'deposit',
    values: [
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: 'emitEventsForFrontOfDepositAndWithdrawalQueues',
    values: [AddressLike],
  ): string;
  encodeFunctionData(functionFragment: 'exchange', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'exitWallet',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'finalizeManagedAccountUpgrade',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'initiateManagedAccountUpgrade',
    values: [BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'intervalTick',
    values: [BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'isAddManagedAccountEnabled',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'isApplyDepositEnabled',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'isDepositEnabled',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'liquidateManagerWallet',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadSharePrice',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultBalanceForWallet',
    values: [AddressLike, AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultDepositQueueItem',
    values: [AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultDepositQueueLength',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultSummary',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultWithdrawQueueItem',
    values: [AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultWithdrawQueueLength',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'managedAccountUpgradeBlockTimestampDelayInS',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'minimumWithdrawalQuantity',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'ownerWallet',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'removeAdmin',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'removeOwner',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'seenDepositIndexes',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'seenWithdrawalHashes',
    values: [BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'setAddManagedAccountEnabledAdmin',
    values: [boolean],
  ): string;
  encodeFunctionData(
    functionFragment: 'setAdmin',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'setDepositEnabled',
    values: [boolean],
  ): string;
  encodeFunctionData(
    functionFragment: 'setDepositEnabledAdmin',
    values: [boolean, boolean],
  ): string;
  encodeFunctionData(
    functionFragment: 'setManagedAccountUpgradeBlockTimestampDelay',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'setMinimumWithdrawalQuantity',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'setOwner',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'setWithdrawalDispatcher',
    values: [AddressLike],
  ): string;
  encodeFunctionData(functionFragment: 'skim', values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: 'vaultConfigurationUpgradesByManagerWallet',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'withdrawByQuantity',
    values: [WithdrawalFromManagedAccountByQuantityStruct],
  ): string;
  encodeFunctionData(
    functionFragment: 'withdrawByShares',
    values: [WithdrawalFromManagedAccountBySharesStruct],
  ): string;
  encodeFunctionData(
    functionFragment: 'withdrawExit',
    values: [AddressLike, AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'withdrawalDispatcherWallet',
    values?: undefined,
  ): string;

  decodeFunctionResult(
    functionFragment: 'INITIAL_SHARE_PRICE',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MAX_CARRY_FEE_MULTIPLIER',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MAX_DEPOSIT_FEE_MULTIPLIER',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MAX_MANAGEMENT_FEE_MULTIPLIER',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MAX_MANAGEMENT_FEE_PERIOD_IN_S',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MAX_MAXIMUM_NET_DEPOSITS',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MAX_MINIMUM_UNAPPLIED_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MAX_MINIMUM_WITHDRAWAL_QUANTITY',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MIN_MANAGEMENT_FEE_PERIOD_IN_S',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MIN_MAXIMUM_NET_DEPOSITS',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MIN_MINIMUM_UNAPPLIED_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'MIN_MINIMUM_WITHDRAWAL_QUANTITY',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'WORD_SIZE_IN_BYTES',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'addManagedAccount',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'adminWallet',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'applyPendingDeposit',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'applyPendingWithdrawal',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'cancelManagedAccountUpgrade',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'cancelPendingWithdrawal',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'emitEventsForFrontOfDepositAndWithdrawalQueues',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'exchange', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'exitWallet', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'finalizeManagedAccountUpgrade',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'initiateManagedAccountUpgrade',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'intervalTick',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'isAddManagedAccountEnabled',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'isApplyDepositEnabled',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'isDepositEnabled',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'liquidateManagerWallet',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadSharePrice',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultBalanceForWallet',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultDepositQueueItem',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultDepositQueueLength',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultSummary',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultWithdrawQueueItem',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultWithdrawQueueLength',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'managedAccountUpgradeBlockTimestampDelayInS',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'minimumWithdrawalQuantity',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'ownerWallet',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'removeAdmin',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'removeOwner',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'seenDepositIndexes',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'seenWithdrawalHashes',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setAddManagedAccountEnabledAdmin',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'setAdmin', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'setDepositEnabled',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setDepositEnabledAdmin',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setManagedAccountUpgradeBlockTimestampDelay',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setMinimumWithdrawalQuantity',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'setOwner', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'setWithdrawalDispatcher',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'skim', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'vaultConfigurationUpgradesByManagerWallet',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'withdrawByQuantity',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'withdrawByShares',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'withdrawExit',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'withdrawalDispatcherWallet',
    data: BytesLike,
  ): Result;
}

export namespace AddManagedAccountsDisabledAdminEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AddManagedAccountsEnabledAdminEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositToManagedAccountReadyToApplyEvent {
  export type InputTuple = [
    depositIndex: BigNumberish,
    quantity: BigNumberish,
    sourceWallet: AddressLike,
    depositorWallet: AddressLike,
    managerWallet: AddressLike,
  ];
  export type OutputTuple = [
    depositIndex: bigint,
    quantity: bigint,
    sourceWallet: string,
    depositorWallet: string,
    managerWallet: string,
  ];
  export interface OutputObject {
    depositIndex: bigint;
    quantity: bigint;
    sourceWallet: string;
    depositorWallet: string;
    managerWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositsDisabledEvent {
  export type InputTuple = [managerWallet: AddressLike];
  export type OutputTuple = [managerWallet: string];
  export interface OutputObject {
    managerWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositsDisabledAdminEvent {
  export type InputTuple = [
    isDepositEnabled: boolean,
    isApplyDepositEnabled: boolean,
  ];
  export type OutputTuple = [
    isDepositEnabled: boolean,
    isApplyDepositEnabled: boolean,
  ];
  export interface OutputObject {
    isDepositEnabled: boolean;
    isApplyDepositEnabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositsEnabledEvent {
  export type InputTuple = [managerWallet: AddressLike];
  export type OutputTuple = [managerWallet: string];
  export interface OutputObject {
    managerWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositsEnabledAdminEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidatedVaultPendingDepositRefundFailedEvent {
  export type InputTuple = [
    depositorWallet: AddressLike,
    quantityInAssetUnits: BigNumberish,
    depositErrorData: BytesLike,
  ];
  export type OutputTuple = [
    depositorWallet: string,
    quantityInAssetUnits: bigint,
    depositErrorData: string,
  ];
  export interface OutputObject {
    depositorWallet: string;
    quantityInAssetUnits: bigint;
    depositErrorData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagedAccountAddedEvent {
  export type InputTuple = [managerWallet: AddressLike];
  export type OutputTuple = [managerWallet: string];
  export interface OutputObject {
    managerWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagedAccountUpgradeBlockTimestampDelayChangedEvent {
  export type InputTuple = [
    previousValue: BigNumberish,
    newValue: BigNumberish,
  ];
  export type OutputTuple = [previousValue: bigint, newValue: bigint];
  export interface OutputObject {
    previousValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagedAccountUpgradeCanceledEvent {
  export type InputTuple = [managerWallet: AddressLike];
  export type OutputTuple = [managerWallet: string];
  export interface OutputObject {
    managerWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagedAccountUpgradeFinalizedEvent {
  export type InputTuple = [managerWallet: AddressLike];
  export type OutputTuple = [managerWallet: string];
  export interface OutputObject {
    managerWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagedAccountUpgradeInitiatedEvent {
  export type InputTuple = [
    managerWallet: AddressLike,
    blockTimestampThreshold: BigNumberish,
  ];
  export type OutputTuple = [
    managerWallet: string,
    blockTimestampThreshold: bigint,
  ];
  export interface OutputObject {
    managerWallet: string;
    blockTimestampThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinimumWithdrawalQuantityChangedEvent {
  export type InputTuple = [
    previousValue: BigNumberish,
    newValue: BigNumberish,
  ];
  export type OutputTuple = [previousValue: bigint, newValue: bigint];
  export interface OutputObject {
    previousValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultLiquidatedEvent {
  export type InputTuple = [managerWallet: AddressLike];
  export type OutputTuple = [managerWallet: string];
  export interface OutputObject {
    managerWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultSharesBurnedEvent {
  export type InputTuple = [
    managerWallet: AddressLike,
    depositorWallet: AddressLike,
    sharesBurned: BigNumberish,
    quoteQuantity: BigNumberish,
    totalSharesForWallet: BigNumberish,
    totalSharesForVault: BigNumberish,
  ];
  export type OutputTuple = [
    managerWallet: string,
    depositorWallet: string,
    sharesBurned: bigint,
    quoteQuantity: bigint,
    totalSharesForWallet: bigint,
    totalSharesForVault: bigint,
  ];
  export interface OutputObject {
    managerWallet: string;
    depositorWallet: string;
    sharesBurned: bigint;
    quoteQuantity: bigint;
    totalSharesForWallet: bigint;
    totalSharesForVault: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultSharesMintedEvent {
  export type InputTuple = [
    managerWallet: AddressLike,
    depositorWallet: AddressLike,
    sharesMinted: BigNumberish,
    totalSharesForWallet: BigNumberish,
    totalSharesForVault: BigNumberish,
  ];
  export type OutputTuple = [
    managerWallet: string,
    depositorWallet: string,
    sharesMinted: bigint,
    totalSharesForWallet: bigint,
    totalSharesForVault: bigint,
  ];
  export interface OutputObject {
    managerWallet: string;
    depositorWallet: string;
    sharesMinted: bigint;
    totalSharesForWallet: bigint;
    totalSharesForVault: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalDispatcherChangedEvent {
  export type InputTuple = [previousValue: AddressLike, newValue: AddressLike];
  export type OutputTuple = [previousValue: string, newValue: string];
  export interface OutputObject {
    previousValue: string;
    newValue: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalFromManagedAccountCanceledEvent {
  export type InputTuple = [
    managerWallet: AddressLike,
    depositorWallet: AddressLike,
    shares: BigNumberish,
  ];
  export type OutputTuple = [
    managerWallet: string,
    depositorWallet: string,
    shares: bigint,
  ];
  export interface OutputObject {
    managerWallet: string;
    depositorWallet: string;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalFromManagedAccountReadyToApplyEvent {
  export type InputTuple = [
    withdrawal: WithdrawalFromManagedAccountStruct,
    totalShareSupply: BigNumberish,
    numberOfWithdrawalsInQueue: BigNumberish,
  ];
  export type OutputTuple = [
    withdrawal: WithdrawalFromManagedAccountStructOutput,
    totalShareSupply: bigint,
    numberOfWithdrawalsInQueue: bigint,
  ];
  export interface OutputObject {
    withdrawal: WithdrawalFromManagedAccountStructOutput;
    totalShareSupply: bigint;
    numberOfWithdrawalsInQueue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProfitShareVaultProvider_v1 extends BaseContract {
  connect(runner?: ContractRunner | null): ProfitShareVaultProvider_v1;
  waitForDeployment(): Promise<this>;

  interface: ProfitShareVaultProvider_v1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  INITIAL_SHARE_PRICE: TypedContractMethod<[], [bigint], 'view'>;

  MAX_CARRY_FEE_MULTIPLIER: TypedContractMethod<[], [bigint], 'view'>;

  MAX_DEPOSIT_FEE_MULTIPLIER: TypedContractMethod<[], [bigint], 'view'>;

  MAX_MANAGEMENT_FEE_MULTIPLIER: TypedContractMethod<[], [bigint], 'view'>;

  MAX_MANAGEMENT_FEE_PERIOD_IN_S: TypedContractMethod<[], [bigint], 'view'>;

  MAX_MAXIMUM_NET_DEPOSITS: TypedContractMethod<[], [bigint], 'view'>;

  MAX_MINIMUM_UNAPPLIED_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  MAX_MINIMUM_WITHDRAWAL_QUANTITY: TypedContractMethod<[], [bigint], 'view'>;

  MIN_MANAGEMENT_FEE_PERIOD_IN_S: TypedContractMethod<[], [bigint], 'view'>;

  MIN_MAXIMUM_NET_DEPOSITS: TypedContractMethod<[], [bigint], 'view'>;

  MIN_MINIMUM_UNAPPLIED_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  MIN_MINIMUM_WITHDRAWAL_QUANTITY: TypedContractMethod<[], [bigint], 'view'>;

  WORD_SIZE_IN_BYTES: TypedContractMethod<[], [bigint], 'view'>;

  addManagedAccount: TypedContractMethod<
    [managerWallet: AddressLike, payload: BytesLike],
    [void],
    'nonpayable'
  >;

  adminWallet: TypedContractMethod<[], [string], 'view'>;

  applyPendingDeposit: TypedContractMethod<
    [
      depositIndex: BigNumberish,
      managerWallet: AddressLike,
      quantity: BigNumberish,
    ],
    [void],
    'nonpayable'
  >;

  applyPendingWithdrawal: TypedContractMethod<
    [
      gasFee: BigNumberish,
      grossQuantity: BigNumberish,
      managerWallet: AddressLike,
      withdrawalHash: BytesLike,
    ],
    [void],
    'nonpayable'
  >;

  cancelManagedAccountUpgrade: TypedContractMethod<[], [void], 'nonpayable'>;

  cancelPendingWithdrawal: TypedContractMethod<
    [
      gasFee: BigNumberish,
      managerWallet: AddressLike,
      withdrawalHash: BytesLike,
    ],
    [void],
    'nonpayable'
  >;

  deposit: TypedContractMethod<
    [
      depositIndex: BigNumberish,
      quantity: BigNumberish,
      sourceWallet: AddressLike,
      depositorWallet: AddressLike,
      managerWallet: AddressLike,
      payload: BytesLike,
    ],
    [void],
    'nonpayable'
  >;

  emitEventsForFrontOfDepositAndWithdrawalQueues: TypedContractMethod<
    [managerWallet: AddressLike],
    [void],
    'nonpayable'
  >;

  exchange: TypedContractMethod<[], [string], 'view'>;

  exitWallet: TypedContractMethod<
    [managerWallet: AddressLike],
    [void],
    'nonpayable'
  >;

  finalizeManagedAccountUpgrade: TypedContractMethod<[], [void], 'nonpayable'>;

  initiateManagedAccountUpgrade: TypedContractMethod<
    [payload: BytesLike],
    [void],
    'nonpayable'
  >;

  intervalTick: TypedContractMethod<[payload: BytesLike], [void], 'nonpayable'>;

  isAddManagedAccountEnabled: TypedContractMethod<[], [boolean], 'view'>;

  isApplyDepositEnabled: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    'view'
  >;

  isDepositEnabled: TypedContractMethod<
    [managerWallet: AddressLike],
    [boolean],
    'view'
  >;

  liquidateManagerWallet: TypedContractMethod<
    [managerWallet: AddressLike],
    [void],
    'nonpayable'
  >;

  loadSharePrice: TypedContractMethod<
    [managerWallet: AddressLike],
    [bigint],
    'view'
  >;

  loadVaultBalanceForWallet: TypedContractMethod<
    [managerWallet: AddressLike, depositorWallet: AddressLike],
    [ProfitShareVaultProvider_v1.VaultBalanceForWalletStructOutput],
    'view'
  >;

  loadVaultDepositQueueItem: TypedContractMethod<
    [managerWallet: AddressLike, index: BigNumberish],
    [VaultDepositQueue.ItemStructOutput],
    'view'
  >;

  loadVaultDepositQueueLength: TypedContractMethod<
    [managerWallet: AddressLike],
    [bigint],
    'view'
  >;

  loadVaultSummary: TypedContractMethod<
    [managerWallet: AddressLike],
    [ProfitShareVaultProvider_v1.VaultSummaryStructOutput],
    'view'
  >;

  loadVaultWithdrawQueueItem: TypedContractMethod<
    [managerWallet: AddressLike, index: BigNumberish],
    [WithdrawalFromManagedAccountStructOutput],
    'view'
  >;

  loadVaultWithdrawQueueLength: TypedContractMethod<
    [managerWallet: AddressLike],
    [bigint],
    'view'
  >;

  managedAccountUpgradeBlockTimestampDelayInS: TypedContractMethod<
    [],
    [bigint],
    'view'
  >;

  minimumWithdrawalQuantity: TypedContractMethod<[], [bigint], 'view'>;

  ownerWallet: TypedContractMethod<[], [string], 'view'>;

  removeAdmin: TypedContractMethod<[], [void], 'nonpayable'>;

  removeOwner: TypedContractMethod<[], [void], 'nonpayable'>;

  seenDepositIndexes: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    'view'
  >;

  seenWithdrawalHashes: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    'view'
  >;

  setAddManagedAccountEnabledAdmin: TypedContractMethod<
    [isAddManagedAccountEnabled: boolean],
    [void],
    'nonpayable'
  >;

  setAdmin: TypedContractMethod<[newAdmin: AddressLike], [void], 'nonpayable'>;

  setDepositEnabled: TypedContractMethod<
    [isEnabled: boolean],
    [void],
    'nonpayable'
  >;

  setDepositEnabledAdmin: TypedContractMethod<
    [isDepositEnabled: boolean, isApplyDepositEnabled: boolean],
    [void],
    'nonpayable'
  >;

  setManagedAccountUpgradeBlockTimestampDelay: TypedContractMethod<
    [newManagedAccountUpgradeBlockTimestampDelayInS: BigNumberish],
    [void],
    'nonpayable'
  >;

  setMinimumWithdrawalQuantity: TypedContractMethod<
    [newMinimumWithdrawalQuantity: BigNumberish],
    [void],
    'nonpayable'
  >;

  setOwner: TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;

  setWithdrawalDispatcher: TypedContractMethod<
    [newWithdrawalDispatcherWallet: AddressLike],
    [void],
    'nonpayable'
  >;

  skim: TypedContractMethod<[tokenAddress: AddressLike], [void], 'nonpayable'>;

  vaultConfigurationUpgradesByManagerWallet: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        boolean,
        ProfitShareVaultProvider_v1.VaultConfigurationFieldsStructOutput,
        bigint,
      ] & {
        exists: boolean;
        newVaultConfigurationFields: ProfitShareVaultProvider_v1.VaultConfigurationFieldsStructOutput;
        blockTimestampThreshold: bigint;
      },
    ],
    'view'
  >;

  withdrawByQuantity: TypedContractMethod<
    [arg0: WithdrawalFromManagedAccountByQuantityStruct],
    [void],
    'view'
  >;

  withdrawByShares: TypedContractMethod<
    [withdrawal: WithdrawalFromManagedAccountBySharesStruct],
    [void],
    'nonpayable'
  >;

  withdrawExit: TypedContractMethod<
    [managerWallet: AddressLike, depositorWallet: AddressLike],
    [void],
    'nonpayable'
  >;

  withdrawalDispatcherWallet: TypedContractMethod<[], [string], 'view'>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: 'INITIAL_SHARE_PRICE',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MAX_CARRY_FEE_MULTIPLIER',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MAX_DEPOSIT_FEE_MULTIPLIER',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MAX_MANAGEMENT_FEE_MULTIPLIER',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MAX_MANAGEMENT_FEE_PERIOD_IN_S',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MAX_MAXIMUM_NET_DEPOSITS',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MAX_MINIMUM_UNAPPLIED_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MAX_MINIMUM_WITHDRAWAL_QUANTITY',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MIN_MANAGEMENT_FEE_PERIOD_IN_S',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MIN_MAXIMUM_NET_DEPOSITS',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MIN_MINIMUM_UNAPPLIED_WITHDRAWAL_AGE_IN_S_TO_INITIATE_EXIT',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'MIN_MINIMUM_WITHDRAWAL_QUANTITY',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'WORD_SIZE_IN_BYTES',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'addManagedAccount',
  ): TypedContractMethod<
    [managerWallet: AddressLike, payload: BytesLike],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'adminWallet',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'applyPendingDeposit',
  ): TypedContractMethod<
    [
      depositIndex: BigNumberish,
      managerWallet: AddressLike,
      quantity: BigNumberish,
    ],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'applyPendingWithdrawal',
  ): TypedContractMethod<
    [
      gasFee: BigNumberish,
      grossQuantity: BigNumberish,
      managerWallet: AddressLike,
      withdrawalHash: BytesLike,
    ],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'cancelManagedAccountUpgrade',
  ): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'cancelPendingWithdrawal',
  ): TypedContractMethod<
    [
      gasFee: BigNumberish,
      managerWallet: AddressLike,
      withdrawalHash: BytesLike,
    ],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'deposit',
  ): TypedContractMethod<
    [
      depositIndex: BigNumberish,
      quantity: BigNumberish,
      sourceWallet: AddressLike,
      depositorWallet: AddressLike,
      managerWallet: AddressLike,
      payload: BytesLike,
    ],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'emitEventsForFrontOfDepositAndWithdrawalQueues',
  ): TypedContractMethod<[managerWallet: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'exchange',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'exitWallet',
  ): TypedContractMethod<[managerWallet: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'finalizeManagedAccountUpgrade',
  ): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'initiateManagedAccountUpgrade',
  ): TypedContractMethod<[payload: BytesLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'intervalTick',
  ): TypedContractMethod<[payload: BytesLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'isAddManagedAccountEnabled',
  ): TypedContractMethod<[], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'isApplyDepositEnabled',
  ): TypedContractMethod<[arg0: AddressLike], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'isDepositEnabled',
  ): TypedContractMethod<[managerWallet: AddressLike], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'liquidateManagerWallet',
  ): TypedContractMethod<[managerWallet: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'loadSharePrice',
  ): TypedContractMethod<[managerWallet: AddressLike], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'loadVaultBalanceForWallet',
  ): TypedContractMethod<
    [managerWallet: AddressLike, depositorWallet: AddressLike],
    [ProfitShareVaultProvider_v1.VaultBalanceForWalletStructOutput],
    'view'
  >;
  getFunction(
    nameOrSignature: 'loadVaultDepositQueueItem',
  ): TypedContractMethod<
    [managerWallet: AddressLike, index: BigNumberish],
    [VaultDepositQueue.ItemStructOutput],
    'view'
  >;
  getFunction(
    nameOrSignature: 'loadVaultDepositQueueLength',
  ): TypedContractMethod<[managerWallet: AddressLike], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'loadVaultSummary',
  ): TypedContractMethod<
    [managerWallet: AddressLike],
    [ProfitShareVaultProvider_v1.VaultSummaryStructOutput],
    'view'
  >;
  getFunction(
    nameOrSignature: 'loadVaultWithdrawQueueItem',
  ): TypedContractMethod<
    [managerWallet: AddressLike, index: BigNumberish],
    [WithdrawalFromManagedAccountStructOutput],
    'view'
  >;
  getFunction(
    nameOrSignature: 'loadVaultWithdrawQueueLength',
  ): TypedContractMethod<[managerWallet: AddressLike], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'managedAccountUpgradeBlockTimestampDelayInS',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'minimumWithdrawalQuantity',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'ownerWallet',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'removeAdmin',
  ): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'removeOwner',
  ): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'seenDepositIndexes',
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'seenWithdrawalHashes',
  ): TypedContractMethod<[arg0: BytesLike], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'setAddManagedAccountEnabledAdmin',
  ): TypedContractMethod<
    [isAddManagedAccountEnabled: boolean],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'setAdmin',
  ): TypedContractMethod<[newAdmin: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setDepositEnabled',
  ): TypedContractMethod<[isEnabled: boolean], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setDepositEnabledAdmin',
  ): TypedContractMethod<
    [isDepositEnabled: boolean, isApplyDepositEnabled: boolean],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'setManagedAccountUpgradeBlockTimestampDelay',
  ): TypedContractMethod<
    [newManagedAccountUpgradeBlockTimestampDelayInS: BigNumberish],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'setMinimumWithdrawalQuantity',
  ): TypedContractMethod<
    [newMinimumWithdrawalQuantity: BigNumberish],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'setOwner',
  ): TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setWithdrawalDispatcher',
  ): TypedContractMethod<
    [newWithdrawalDispatcherWallet: AddressLike],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'skim',
  ): TypedContractMethod<[tokenAddress: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'vaultConfigurationUpgradesByManagerWallet',
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        boolean,
        ProfitShareVaultProvider_v1.VaultConfigurationFieldsStructOutput,
        bigint,
      ] & {
        exists: boolean;
        newVaultConfigurationFields: ProfitShareVaultProvider_v1.VaultConfigurationFieldsStructOutput;
        blockTimestampThreshold: bigint;
      },
    ],
    'view'
  >;
  getFunction(
    nameOrSignature: 'withdrawByQuantity',
  ): TypedContractMethod<
    [arg0: WithdrawalFromManagedAccountByQuantityStruct],
    [void],
    'view'
  >;
  getFunction(
    nameOrSignature: 'withdrawByShares',
  ): TypedContractMethod<
    [withdrawal: WithdrawalFromManagedAccountBySharesStruct],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'withdrawExit',
  ): TypedContractMethod<
    [managerWallet: AddressLike, depositorWallet: AddressLike],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'withdrawalDispatcherWallet',
  ): TypedContractMethod<[], [string], 'view'>;

  getEvent(
    key: 'AddManagedAccountsDisabledAdmin',
  ): TypedContractEvent<
    AddManagedAccountsDisabledAdminEvent.InputTuple,
    AddManagedAccountsDisabledAdminEvent.OutputTuple,
    AddManagedAccountsDisabledAdminEvent.OutputObject
  >;
  getEvent(
    key: 'AddManagedAccountsEnabledAdmin',
  ): TypedContractEvent<
    AddManagedAccountsEnabledAdminEvent.InputTuple,
    AddManagedAccountsEnabledAdminEvent.OutputTuple,
    AddManagedAccountsEnabledAdminEvent.OutputObject
  >;
  getEvent(
    key: 'DepositToManagedAccountReadyToApply',
  ): TypedContractEvent<
    DepositToManagedAccountReadyToApplyEvent.InputTuple,
    DepositToManagedAccountReadyToApplyEvent.OutputTuple,
    DepositToManagedAccountReadyToApplyEvent.OutputObject
  >;
  getEvent(
    key: 'DepositsDisabled',
  ): TypedContractEvent<
    DepositsDisabledEvent.InputTuple,
    DepositsDisabledEvent.OutputTuple,
    DepositsDisabledEvent.OutputObject
  >;
  getEvent(
    key: 'DepositsDisabledAdmin',
  ): TypedContractEvent<
    DepositsDisabledAdminEvent.InputTuple,
    DepositsDisabledAdminEvent.OutputTuple,
    DepositsDisabledAdminEvent.OutputObject
  >;
  getEvent(
    key: 'DepositsEnabled',
  ): TypedContractEvent<
    DepositsEnabledEvent.InputTuple,
    DepositsEnabledEvent.OutputTuple,
    DepositsEnabledEvent.OutputObject
  >;
  getEvent(
    key: 'DepositsEnabledAdmin',
  ): TypedContractEvent<
    DepositsEnabledAdminEvent.InputTuple,
    DepositsEnabledAdminEvent.OutputTuple,
    DepositsEnabledAdminEvent.OutputObject
  >;
  getEvent(
    key: 'LiquidatedVaultPendingDepositRefundFailed',
  ): TypedContractEvent<
    LiquidatedVaultPendingDepositRefundFailedEvent.InputTuple,
    LiquidatedVaultPendingDepositRefundFailedEvent.OutputTuple,
    LiquidatedVaultPendingDepositRefundFailedEvent.OutputObject
  >;
  getEvent(
    key: 'ManagedAccountAdded',
  ): TypedContractEvent<
    ManagedAccountAddedEvent.InputTuple,
    ManagedAccountAddedEvent.OutputTuple,
    ManagedAccountAddedEvent.OutputObject
  >;
  getEvent(
    key: 'ManagedAccountUpgradeBlockTimestampDelayChanged',
  ): TypedContractEvent<
    ManagedAccountUpgradeBlockTimestampDelayChangedEvent.InputTuple,
    ManagedAccountUpgradeBlockTimestampDelayChangedEvent.OutputTuple,
    ManagedAccountUpgradeBlockTimestampDelayChangedEvent.OutputObject
  >;
  getEvent(
    key: 'ManagedAccountUpgradeCanceled',
  ): TypedContractEvent<
    ManagedAccountUpgradeCanceledEvent.InputTuple,
    ManagedAccountUpgradeCanceledEvent.OutputTuple,
    ManagedAccountUpgradeCanceledEvent.OutputObject
  >;
  getEvent(
    key: 'ManagedAccountUpgradeFinalized',
  ): TypedContractEvent<
    ManagedAccountUpgradeFinalizedEvent.InputTuple,
    ManagedAccountUpgradeFinalizedEvent.OutputTuple,
    ManagedAccountUpgradeFinalizedEvent.OutputObject
  >;
  getEvent(
    key: 'ManagedAccountUpgradeInitiated',
  ): TypedContractEvent<
    ManagedAccountUpgradeInitiatedEvent.InputTuple,
    ManagedAccountUpgradeInitiatedEvent.OutputTuple,
    ManagedAccountUpgradeInitiatedEvent.OutputObject
  >;
  getEvent(
    key: 'MinimumWithdrawalQuantityChanged',
  ): TypedContractEvent<
    MinimumWithdrawalQuantityChangedEvent.InputTuple,
    MinimumWithdrawalQuantityChangedEvent.OutputTuple,
    MinimumWithdrawalQuantityChangedEvent.OutputObject
  >;
  getEvent(
    key: 'VaultLiquidated',
  ): TypedContractEvent<
    VaultLiquidatedEvent.InputTuple,
    VaultLiquidatedEvent.OutputTuple,
    VaultLiquidatedEvent.OutputObject
  >;
  getEvent(
    key: 'VaultSharesBurned',
  ): TypedContractEvent<
    VaultSharesBurnedEvent.InputTuple,
    VaultSharesBurnedEvent.OutputTuple,
    VaultSharesBurnedEvent.OutputObject
  >;
  getEvent(
    key: 'VaultSharesMinted',
  ): TypedContractEvent<
    VaultSharesMintedEvent.InputTuple,
    VaultSharesMintedEvent.OutputTuple,
    VaultSharesMintedEvent.OutputObject
  >;
  getEvent(
    key: 'WithdrawalDispatcherChanged',
  ): TypedContractEvent<
    WithdrawalDispatcherChangedEvent.InputTuple,
    WithdrawalDispatcherChangedEvent.OutputTuple,
    WithdrawalDispatcherChangedEvent.OutputObject
  >;
  getEvent(
    key: 'WithdrawalFromManagedAccountCanceled',
  ): TypedContractEvent<
    WithdrawalFromManagedAccountCanceledEvent.InputTuple,
    WithdrawalFromManagedAccountCanceledEvent.OutputTuple,
    WithdrawalFromManagedAccountCanceledEvent.OutputObject
  >;
  getEvent(
    key: 'WithdrawalFromManagedAccountReadyToApply',
  ): TypedContractEvent<
    WithdrawalFromManagedAccountReadyToApplyEvent.InputTuple,
    WithdrawalFromManagedAccountReadyToApplyEvent.OutputTuple,
    WithdrawalFromManagedAccountReadyToApplyEvent.OutputObject
  >;

  filters: {
    'AddManagedAccountsDisabledAdmin()': TypedContractEvent<
      AddManagedAccountsDisabledAdminEvent.InputTuple,
      AddManagedAccountsDisabledAdminEvent.OutputTuple,
      AddManagedAccountsDisabledAdminEvent.OutputObject
    >;
    AddManagedAccountsDisabledAdmin: TypedContractEvent<
      AddManagedAccountsDisabledAdminEvent.InputTuple,
      AddManagedAccountsDisabledAdminEvent.OutputTuple,
      AddManagedAccountsDisabledAdminEvent.OutputObject
    >;

    'AddManagedAccountsEnabledAdmin()': TypedContractEvent<
      AddManagedAccountsEnabledAdminEvent.InputTuple,
      AddManagedAccountsEnabledAdminEvent.OutputTuple,
      AddManagedAccountsEnabledAdminEvent.OutputObject
    >;
    AddManagedAccountsEnabledAdmin: TypedContractEvent<
      AddManagedAccountsEnabledAdminEvent.InputTuple,
      AddManagedAccountsEnabledAdminEvent.OutputTuple,
      AddManagedAccountsEnabledAdminEvent.OutputObject
    >;

    'DepositToManagedAccountReadyToApply(uint64,uint64,address,address,address)': TypedContractEvent<
      DepositToManagedAccountReadyToApplyEvent.InputTuple,
      DepositToManagedAccountReadyToApplyEvent.OutputTuple,
      DepositToManagedAccountReadyToApplyEvent.OutputObject
    >;
    DepositToManagedAccountReadyToApply: TypedContractEvent<
      DepositToManagedAccountReadyToApplyEvent.InputTuple,
      DepositToManagedAccountReadyToApplyEvent.OutputTuple,
      DepositToManagedAccountReadyToApplyEvent.OutputObject
    >;

    'DepositsDisabled(address)': TypedContractEvent<
      DepositsDisabledEvent.InputTuple,
      DepositsDisabledEvent.OutputTuple,
      DepositsDisabledEvent.OutputObject
    >;
    DepositsDisabled: TypedContractEvent<
      DepositsDisabledEvent.InputTuple,
      DepositsDisabledEvent.OutputTuple,
      DepositsDisabledEvent.OutputObject
    >;

    'DepositsDisabledAdmin(bool,bool)': TypedContractEvent<
      DepositsDisabledAdminEvent.InputTuple,
      DepositsDisabledAdminEvent.OutputTuple,
      DepositsDisabledAdminEvent.OutputObject
    >;
    DepositsDisabledAdmin: TypedContractEvent<
      DepositsDisabledAdminEvent.InputTuple,
      DepositsDisabledAdminEvent.OutputTuple,
      DepositsDisabledAdminEvent.OutputObject
    >;

    'DepositsEnabled(address)': TypedContractEvent<
      DepositsEnabledEvent.InputTuple,
      DepositsEnabledEvent.OutputTuple,
      DepositsEnabledEvent.OutputObject
    >;
    DepositsEnabled: TypedContractEvent<
      DepositsEnabledEvent.InputTuple,
      DepositsEnabledEvent.OutputTuple,
      DepositsEnabledEvent.OutputObject
    >;

    'DepositsEnabledAdmin()': TypedContractEvent<
      DepositsEnabledAdminEvent.InputTuple,
      DepositsEnabledAdminEvent.OutputTuple,
      DepositsEnabledAdminEvent.OutputObject
    >;
    DepositsEnabledAdmin: TypedContractEvent<
      DepositsEnabledAdminEvent.InputTuple,
      DepositsEnabledAdminEvent.OutputTuple,
      DepositsEnabledAdminEvent.OutputObject
    >;

    'LiquidatedVaultPendingDepositRefundFailed(address,uint256,bytes)': TypedContractEvent<
      LiquidatedVaultPendingDepositRefundFailedEvent.InputTuple,
      LiquidatedVaultPendingDepositRefundFailedEvent.OutputTuple,
      LiquidatedVaultPendingDepositRefundFailedEvent.OutputObject
    >;
    LiquidatedVaultPendingDepositRefundFailed: TypedContractEvent<
      LiquidatedVaultPendingDepositRefundFailedEvent.InputTuple,
      LiquidatedVaultPendingDepositRefundFailedEvent.OutputTuple,
      LiquidatedVaultPendingDepositRefundFailedEvent.OutputObject
    >;

    'ManagedAccountAdded(address)': TypedContractEvent<
      ManagedAccountAddedEvent.InputTuple,
      ManagedAccountAddedEvent.OutputTuple,
      ManagedAccountAddedEvent.OutputObject
    >;
    ManagedAccountAdded: TypedContractEvent<
      ManagedAccountAddedEvent.InputTuple,
      ManagedAccountAddedEvent.OutputTuple,
      ManagedAccountAddedEvent.OutputObject
    >;

    'ManagedAccountUpgradeBlockTimestampDelayChanged(uint256,uint256)': TypedContractEvent<
      ManagedAccountUpgradeBlockTimestampDelayChangedEvent.InputTuple,
      ManagedAccountUpgradeBlockTimestampDelayChangedEvent.OutputTuple,
      ManagedAccountUpgradeBlockTimestampDelayChangedEvent.OutputObject
    >;
    ManagedAccountUpgradeBlockTimestampDelayChanged: TypedContractEvent<
      ManagedAccountUpgradeBlockTimestampDelayChangedEvent.InputTuple,
      ManagedAccountUpgradeBlockTimestampDelayChangedEvent.OutputTuple,
      ManagedAccountUpgradeBlockTimestampDelayChangedEvent.OutputObject
    >;

    'ManagedAccountUpgradeCanceled(address)': TypedContractEvent<
      ManagedAccountUpgradeCanceledEvent.InputTuple,
      ManagedAccountUpgradeCanceledEvent.OutputTuple,
      ManagedAccountUpgradeCanceledEvent.OutputObject
    >;
    ManagedAccountUpgradeCanceled: TypedContractEvent<
      ManagedAccountUpgradeCanceledEvent.InputTuple,
      ManagedAccountUpgradeCanceledEvent.OutputTuple,
      ManagedAccountUpgradeCanceledEvent.OutputObject
    >;

    'ManagedAccountUpgradeFinalized(address)': TypedContractEvent<
      ManagedAccountUpgradeFinalizedEvent.InputTuple,
      ManagedAccountUpgradeFinalizedEvent.OutputTuple,
      ManagedAccountUpgradeFinalizedEvent.OutputObject
    >;
    ManagedAccountUpgradeFinalized: TypedContractEvent<
      ManagedAccountUpgradeFinalizedEvent.InputTuple,
      ManagedAccountUpgradeFinalizedEvent.OutputTuple,
      ManagedAccountUpgradeFinalizedEvent.OutputObject
    >;

    'ManagedAccountUpgradeInitiated(address,uint256)': TypedContractEvent<
      ManagedAccountUpgradeInitiatedEvent.InputTuple,
      ManagedAccountUpgradeInitiatedEvent.OutputTuple,
      ManagedAccountUpgradeInitiatedEvent.OutputObject
    >;
    ManagedAccountUpgradeInitiated: TypedContractEvent<
      ManagedAccountUpgradeInitiatedEvent.InputTuple,
      ManagedAccountUpgradeInitiatedEvent.OutputTuple,
      ManagedAccountUpgradeInitiatedEvent.OutputObject
    >;

    'MinimumWithdrawalQuantityChanged(uint256,uint256)': TypedContractEvent<
      MinimumWithdrawalQuantityChangedEvent.InputTuple,
      MinimumWithdrawalQuantityChangedEvent.OutputTuple,
      MinimumWithdrawalQuantityChangedEvent.OutputObject
    >;
    MinimumWithdrawalQuantityChanged: TypedContractEvent<
      MinimumWithdrawalQuantityChangedEvent.InputTuple,
      MinimumWithdrawalQuantityChangedEvent.OutputTuple,
      MinimumWithdrawalQuantityChangedEvent.OutputObject
    >;

    'VaultLiquidated(address)': TypedContractEvent<
      VaultLiquidatedEvent.InputTuple,
      VaultLiquidatedEvent.OutputTuple,
      VaultLiquidatedEvent.OutputObject
    >;
    VaultLiquidated: TypedContractEvent<
      VaultLiquidatedEvent.InputTuple,
      VaultLiquidatedEvent.OutputTuple,
      VaultLiquidatedEvent.OutputObject
    >;

    'VaultSharesBurned(address,address,uint64,uint64,uint64,uint64)': TypedContractEvent<
      VaultSharesBurnedEvent.InputTuple,
      VaultSharesBurnedEvent.OutputTuple,
      VaultSharesBurnedEvent.OutputObject
    >;
    VaultSharesBurned: TypedContractEvent<
      VaultSharesBurnedEvent.InputTuple,
      VaultSharesBurnedEvent.OutputTuple,
      VaultSharesBurnedEvent.OutputObject
    >;

    'VaultSharesMinted(address,address,uint64,uint64,uint64)': TypedContractEvent<
      VaultSharesMintedEvent.InputTuple,
      VaultSharesMintedEvent.OutputTuple,
      VaultSharesMintedEvent.OutputObject
    >;
    VaultSharesMinted: TypedContractEvent<
      VaultSharesMintedEvent.InputTuple,
      VaultSharesMintedEvent.OutputTuple,
      VaultSharesMintedEvent.OutputObject
    >;

    'WithdrawalDispatcherChanged(address,address)': TypedContractEvent<
      WithdrawalDispatcherChangedEvent.InputTuple,
      WithdrawalDispatcherChangedEvent.OutputTuple,
      WithdrawalDispatcherChangedEvent.OutputObject
    >;
    WithdrawalDispatcherChanged: TypedContractEvent<
      WithdrawalDispatcherChangedEvent.InputTuple,
      WithdrawalDispatcherChangedEvent.OutputTuple,
      WithdrawalDispatcherChangedEvent.OutputObject
    >;

    'WithdrawalFromManagedAccountCanceled(address,address,uint64)': TypedContractEvent<
      WithdrawalFromManagedAccountCanceledEvent.InputTuple,
      WithdrawalFromManagedAccountCanceledEvent.OutputTuple,
      WithdrawalFromManagedAccountCanceledEvent.OutputObject
    >;
    WithdrawalFromManagedAccountCanceled: TypedContractEvent<
      WithdrawalFromManagedAccountCanceledEvent.InputTuple,
      WithdrawalFromManagedAccountCanceledEvent.OutputTuple,
      WithdrawalFromManagedAccountCanceledEvent.OutputObject
    >;

    'WithdrawalFromManagedAccountReadyToApply(tuple,uint64,uint256)': TypedContractEvent<
      WithdrawalFromManagedAccountReadyToApplyEvent.InputTuple,
      WithdrawalFromManagedAccountReadyToApplyEvent.OutputTuple,
      WithdrawalFromManagedAccountReadyToApplyEvent.OutputObject
    >;
    WithdrawalFromManagedAccountReadyToApply: TypedContractEvent<
      WithdrawalFromManagedAccountReadyToApplyEvent.InputTuple,
      WithdrawalFromManagedAccountReadyToApplyEvent.OutputTuple,
      WithdrawalFromManagedAccountReadyToApplyEvent.OutputObject
    >;
  };
}
