/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from './common';

export type LoadSharePricesAndTotalSharesResultStruct = {
  sharePrice: BigNumberish;
  totalShares: BigNumberish;
};

export type LoadSharePricesAndTotalSharesResultStructOutput = [
  sharePrice: bigint,
  totalShares: bigint,
] & { sharePrice: bigint; totalShares: bigint };

export type LoadVaultDepositorsResultStruct = {
  costBasis: BigNumberish;
  sharePrice: BigNumberish;
  totalShares: BigNumberish;
};

export type LoadVaultDepositorsResultStructOutput = [
  costBasis: bigint,
  sharePrice: bigint,
  totalShares: bigint,
] & { costBasis: bigint; sharePrice: bigint; totalShares: bigint };

export type VaultWithdrawQueueItemStruct = {
  nonce: BigNumberish;
  depositorWallet: AddressLike;
  shares: BigNumberish;
  minimumQuantity: BigNumberish;
};

export type VaultWithdrawQueueItemStructOutput = [
  nonce: bigint,
  depositorWallet: string,
  shares: bigint,
  minimumQuantity: bigint,
] & {
  nonce: bigint;
  depositorWallet: string;
  shares: bigint;
  minimumQuantity: bigint;
};

export interface ProfitShareVaultProviderStateAggregator_v1Interface
  extends Interface {
  getFunction(
    nameOrSignature:
      | 'loadSharePricesAndTotalSharesByVaults'
      | 'loadVaultDepositorsByDepositorWallet'
      | 'loadVaultDepositorsByManagerWallet'
      | 'loadVaultWithdrawalQueue'
      | 'profitShareVaultProvider',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'loadSharePricesAndTotalSharesByVaults',
    values: [AddressLike[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultDepositorsByDepositorWallet',
    values: [AddressLike[], AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultDepositorsByManagerWallet',
    values: [AddressLike, AddressLike[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'loadVaultWithdrawalQueue',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'profitShareVaultProvider',
    values?: undefined,
  ): string;

  decodeFunctionResult(
    functionFragment: 'loadSharePricesAndTotalSharesByVaults',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultDepositorsByDepositorWallet',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultDepositorsByManagerWallet',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'loadVaultWithdrawalQueue',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'profitShareVaultProvider',
    data: BytesLike,
  ): Result;
}

export interface ProfitShareVaultProviderStateAggregator_v1
  extends BaseContract {
  connect(
    runner?: ContractRunner | null,
  ): ProfitShareVaultProviderStateAggregator_v1;
  waitForDeployment(): Promise<this>;

  interface: ProfitShareVaultProviderStateAggregator_v1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  loadSharePricesAndTotalSharesByVaults: TypedContractMethod<
    [managerWallets: AddressLike[]],
    [LoadSharePricesAndTotalSharesResultStructOutput[]],
    'view'
  >;

  loadVaultDepositorsByDepositorWallet: TypedContractMethod<
    [managerWallets: AddressLike[], wallet: AddressLike],
    [LoadVaultDepositorsResultStructOutput[]],
    'view'
  >;

  loadVaultDepositorsByManagerWallet: TypedContractMethod<
    [managerWallet: AddressLike, wallets: AddressLike[]],
    [LoadVaultDepositorsResultStructOutput[]],
    'view'
  >;

  loadVaultWithdrawalQueue: TypedContractMethod<
    [managerWallet: AddressLike],
    [VaultWithdrawQueueItemStructOutput[]],
    'view'
  >;

  profitShareVaultProvider: TypedContractMethod<[], [string], 'view'>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: 'loadSharePricesAndTotalSharesByVaults',
  ): TypedContractMethod<
    [managerWallets: AddressLike[]],
    [LoadSharePricesAndTotalSharesResultStructOutput[]],
    'view'
  >;
  getFunction(
    nameOrSignature: 'loadVaultDepositorsByDepositorWallet',
  ): TypedContractMethod<
    [managerWallets: AddressLike[], wallet: AddressLike],
    [LoadVaultDepositorsResultStructOutput[]],
    'view'
  >;
  getFunction(
    nameOrSignature: 'loadVaultDepositorsByManagerWallet',
  ): TypedContractMethod<
    [managerWallet: AddressLike, wallets: AddressLike[]],
    [LoadVaultDepositorsResultStructOutput[]],
    'view'
  >;
  getFunction(
    nameOrSignature: 'loadVaultWithdrawalQueue',
  ): TypedContractMethod<
    [managerWallet: AddressLike],
    [VaultWithdrawQueueItemStructOutput[]],
    'view'
  >;
  getFunction(
    nameOrSignature: 'profitShareVaultProvider',
  ): TypedContractMethod<[], [string], 'view'>;

  filters: {};
}
